#+TITLE: Notes for Derived Algebraic Geometry
#+AUTHOR: Parker Lowrey
#+LATEX_HEADER: \usepackage{amsthm}
#+LATEX_HEADER: \usepackage{empheq}
#+LATEX_HEADER: \newtheorem{definition}{Definition}
#+LATEX_HEADER: \newtheorem{examples}{Example}
#+MATHJAX: mathml:t
#+LINK_HOME: index
#+BABEL :exports results

#+HTML: \(\def\coloneqq{:=}\)

- Webpage: www.math.uwo.ca/~plowrey

* Notes for 2012-01-10 - Overview (lies)
:PROPERTIES:
:ID: f62ab3fd-fe80-4bc4-b5e6-dc41ebf05eb1
:END:
- Modern algebraic geometry was formed in 1950s-1960s
- Techniques developed to study algebraic geometry have impacted much
  of modern mathematics
- Analogy
  - Modern Algebraic geometry
    - basic building blocks: commutative ring objects in $Set$ (fancy
      way of saying commutative rings)
  - Derived algebraic geometry
    - Commutative ring objects $Set_\Delta$
  - $Set\subset Set_\Delta$, but not every "topologically" discrete
    object is actually discrete
- Notation: $C$, $D$ categories, write $D^C=Fun(C,D)$ and $D_C=Fun(C^{op},D)$
- Modern Algebraic Geometry
  - Any $R\in CRing$ should be "functors" on some topological space in
    a natural way
  - $F:CRings\rightarrow Top$
    - Problem: Let $k$ be a field, $F(k)$ is a point - i.e. not fully faithful.
    - We really want our target to be Ringed topological spaces
    - Let $RTop$ be the category of ringed topological spaces $(X,O_X)$
    - On a field, $F(k)=(*,k)$.
    - $R\in CRing$, $F(R)=(Spec R,O_{Spec R})$, $\Gamma(O_{Spec R}=R$
    - Let $R$ be a finitely generated $\mathbb{C}$-algebra. This
      implies that $R$ is $\mathbb{C}[x_1,\dotsc,x_n]/I$. If
      $(f_1,\dotsc f_n)=I$, Then the topological space assigned to $R$
      should look something like the common zeros of $f_1,\dotsc,f_n$.
  - Side note on manifolds
    - (Loose) Definition
      - A manifold is a (smooth, anayltic, topological) topological
        space that locally looks like an open set in
        $\mathbb{R}^n$.
      - The various flavours are obtained by restricting the gluing
        maps to various types of functions.
      - What about algebraic manifolds?
        - Is this concept enough to study affine schemes and schemes
          in general? No.
        - Theorem ([[https://en.wikipedia.org/wiki/Noether_normalization_lemma][Noether normalization lemma]])
          - Notation: The topological spaces associated to a Cring $R$
            shall be denoted by $Spec R$ and called the affine scheme
            associated to $R$).
          - Does $Spec R$ (for $R$ a $\mathbb{C}$-algebra) look like
            "an algebraic manifold"?
          - Suppose $R$ has finite degree n, then there exists a
            finite map from $Spec R$ to $\mathbb{A}^n$.
      - Why schemes? Because to build any reasonable notions of
        "algebraic manifold" we need as basic building blocks, we need
        *all* affine schemes.
        - Not so formal definition of scheme: a locally ringed
          topological space that is obtained by gluing affine schemes.
        - What is gluing?
          #+BEGIN_SRC latex :file dag.01.svg
            \begin{diagram}
              C&\rInto B\\
              \dInto\\
              A
            \end{diagram}
          #+END_SRC
          I want "space" $X$ such that $X\rightarrow Y$ is really a map
          #+BEGIN_SRC latex :file dag.02.svg
            \begin{diagram}
              C&\rTo&B\\
              \dTo&&\dTo\\
              A&\rTo&Y
            \end{diagram}
          #+END_SRC
          This is know as a colimit of the first diagram.
          - Example: $A=Spec\mathbb{C}[x]$,
            $B=Spec\mathbb{C}[x^{-1}]$, $C=Spec \mathbb{C}[x,x^{-1}]$
            #+BEGIN_SRC latex :file dag.03.svg
              \begin{diagram}
                Spec\mathbb{C}[x,x^{-1}]&\rTo Spec\mathbb{C}[x^{-1}]\\
                \dTo\\
                Spec\mathbb{C}[x]
              \end{diagram}
            #+END_SRC
            equivalently
            #+BEGIN_SRC latex :file dag.04.svg
              \begin{diagram}
                \mathbb{C}[x,x^{-1}]&\lTo \mathbb{C}[x^{-1}]\\
                \uTo\\
                \mathbb{C}[x]
              \end{diagram}
            #+END_SRC
            - Try colimit in $Aff$. Converting to a statement about rings,
              we are looking for the limit of the above diagram, which is
              $\mathbb{C}, which corresponds to a point.
            - Assume Sch. Now perform gluing.
              $\mathbb{p}$ has a cover by twho copies of $\mathbb{C}$
              which are identified by gluing along $\mathbb{C}^*$.
- Derived algebraic geometry
  - Carry out a similiar program but using $CRing_\Delta$ as
    building blocks rather than $CRing$. Further, since
    $CRing\subset CRing_\Delta$, the theory needs to agree there.
  - Also $E_\infty-rings_\Delta$, $E_infty$-spectra, $c-dg-rings$,
    $E_\infty$-dg-rings, etc.
  - We want functor that assigns to a $R\in CRing_\Delta$ a "ringed"
    topological space $(X,O_x)$ where $O_X$ is a functor from
    $Open_X\rightarrow Set_\Delta$. Rick's theory enters this in an
    integral way.
  - Alternative way of building schemes: to glue objects in $Aff$, a
    natural place to do this is in $Fun(Aff^{op},Set)\supset Aff$
  - Side note: One of Grothendieck's gifts to the mathematical communtity:
    - Given any scheme $X$, $Home(-,X)|_Aff$, so $Sch\subset
      Fun(Aff^{op}Set)$.
    - Quot scheme
    - Pic scheme
  - starts at derived algebraic geometry
    - $dAff := CRing^{op}_\Delta$
    - To create a derived scheme, I glue together derived affine
      schemes in $Fun(dAff^{op}, Set_\Delta)$
    - Toen - Homotopical Algebraic Geometry II
  - An analogy to "locally ringed topological space" is a "locally
    ringed topos"
  - Lurie's DAG define the notion of locally ringed $\infty$-topos
    associated to a $R\in CRing_\Delta$. Perform the gluing in the
    category of locally ringed $\infty$-topos
  - Side note:
    - Ch 1 of $\infty$-topoi => $(\infty,0)-cat are equivalent to
      topological spaces
  - Grothendieck:
    - Given $X$ a topological space.
    - Get fundamental groupoid $\Pi_\infty X$
      - objects are points of $X$
      - morphisms are (parameterized) paths between two points
      - 2-morphisms are homotopies between paths.
      - $n$-morphism are homotopies between homotopies
      - every morphism is invertable up-to homotopy.
* Notes for 2012-01-12 - Affine Schemes I
- Recall $R_{loc}Top$ Category of Locally Ringed spaces
- Main Theorem: $CRings/k^{op}\cong Aff\subset R_{loc}Top/k$
- *Definition*
  - A locally ringed topological space is a pair $(X,\O_X)$ with $X\in
    Top$ and $\O_X\in Shv(X)$, such that $\O_X(U)$ is a unital
    commutative ring and given any $p\in X$, $\O_{X,p$ is a local ring.
  - $\O_{X,p}=\lim_{U\ni p\\U\text{ open}}\O_X(U)$
  - Motivation: $M$ is a smooth compact manifold. Let $C^\infty(M)$ be
    the ring of complex smooth (analytic) functions on $M$.
    - $m\in M$,
      $\delta_m:C^\infty(M)\doubleheadedrightarrow\mathbb{C}:f\mapsto
      f(m)$
    - *Claim* $ker\delta_m$ is a maximal ideal
      - Let $\eufrak{p}\subset M$. In
        particular, we have $f\in\eufrak{p}$ such that
        $\delta_m{f}\ne0$. Since the only primes in $\mathbb{C}$ are
        $0$ and $\mathbb{C}$, and $\delta_m{\eufrak(p)}\ne0$, $\eufrak{p}=C^\infty(M)$.
      - Let $I\subet C^\infty(M)$ be a maximal ideal. Set $Z(f)$ to be
        the zero set of $f$. Let $Z_I=\cap_{f\in I} Z(f)$.
        - Case $Z_I\ne0$: Let $m\in Z_I$. Then $I\subset\ker\delta_m$,
          so $I=\ker\delta_m$.
        - Case $Z_i=\emptyset$: Let $D(f)=M\setminus Z(f)$. Then
          $D(f)$ is open. $Z_i=\emptyset$ iff $\bigcup_fD(f)$ is a
          covering. Let $f_1,\dotsc,f_n$ correspond to a choice of
          finite subcovering.
          $$g=\overline{f_1}f_1+\overline{f_2}f_2+\cdots+\overline{f_n}f_n\in I$$
          Then $g$ is non-zero everywhere, so $g$ is invertible and
          $1\in I$.
    - To recover $M$ as a set, we just need to look at maximal ideals
      of $C^\infty(M)$.
    - Assumption: Every point of $\mathbb{C}$ is closed.
    - Using this, we know for each $f\in C^\infty(M)$, $Z(f)$ is
      closed (if $f$ is continuous). Therefor $D(f)$ is open.
    - If we let $\{D(f)\}$ be a sub-basis, we recover a topology on
      $M$ for which $C^\infty(M)$ are continuous.
  - What have we learned?
    - Given $R$ a finitely generated $\mathbb{C}$-algebra. The
      "points" of $Spec R$ (the space we want to create) should
      correspond to maximal ideals.
    - We'll label this set as $Spec_mR$.
  - Let $f\in R$ and suppose $(f)$ is prime.
    - Algebra Viewpoint: $R\rightarrow R/(f)\rightarrow k$, $f$ prime implies
      $R/(f)$ is an integral domain, so has quotient field $k$.
      - There is no natural map $Spec_m k\rightarrow Spec_mR$.
      - To get this morphism, we need to add a "point" $(*,k)$ to $Spec_mR$
      - So, this leads us to the definition of an affine scheme.
        $|Spec R|=\{\eufrak{p}\in R\|\text{\eufrak{p}\text{is a prime ideal}\}$
    - Generate topology by functions from $Spec R\rightarrow \mathbb{C}$
      - $\mathbb{C}=Spec \mathbb{C}[t]$. Assume every point (besides
        the generic point is closed).
      - Want $Aff=CRing^{op}$. In $\mathbb{C}-Alg$,
        $Hom(\mathbb{C}[t], R) = R$.
      - So any $f\in R$ should correspond to a morphism $Spec
        R\rightarrow \mathbb{C}$
      - Copy what we did for smooth compact mainfolds. Since $0$ is
        closed in $\mathbb{C}$.
        - Side Note: How does a map get generated from $f\in R$?
          - Define $f(\eufrak{p})$ for $\eufrak{p}$ maximal, to be the
            image of $f$ in $R/\eufrak{p}$.
          - For non-maximal ideals, if $f\in R/\eufrak{p}$ is
            "constant" (is in the image of $\mathbb{C}\rightarrow R/\eufrak{p}$, send $\eufrak{p}$ to that value. If image of
            $f$ is not constant, then send $\eufrak{p}$ to the generic point.
        - Now, define $Z(f)$ as preimage of 0. Define $D(f)$ as
          $SpecR\setminus Z(f)$. Define topology on $Spec R$ as that
          generated from $\{D(f)\}$.
      - $Spec R$ is a topological space. We still need to define sheaf
        of rings.
        - Observe: Given $f\in R$, $\overline{f}:Spec R\rightarrow
          \mathbb{C}$ and $\overline{f}(D(f))\subet
          \mathbb{C}\setminus 0$. So $\overline(f)$ should be
          invertible. $Spec R_f=D(f)$.
          - $D(f)$ will be the primes not containing $f$. This
            observation says that functions on $D(f)=R_f$.
        - Open sets of $Spec R$ are such that
          each element is of the form $D(f)$ for some $f\in R$.
        - $\O_{Specc R)(D(f)) = R_f$. Now, sheafify to get sheaf on
          $Spec R$.
        - Sanity check: Proposition 2.2 in Hartshorne.
          1) For any $\eufrak{p}\in Spec R$, the stalk is a local ring.
          2) For any element $f\in R$, the ring $\O(D(f))$ is
             isomorphic to $R_f$
        - In particular, setting $f=1$, $D(f)=Spec R, so $\O_{Spec
          R}(Spec R)=R$.
        - $\lim_{U\text{ open}\\p\in U} \O_{Spec R}(U)=R_{\eufrak{p}$ a local ring.
        - We have a map (of sets) $K-alg\rightarrow R_{loc}Top$
          - Given $(X,\O_X)$ and $(Y,\O_Y)$, a morphism (in $RTop$) is
            a pair $(f,f^\sharp)$, with $f\in Hom_{Top}(X,Y)$ and
            $f^\sharp:O_Y\rightarrow f_*\O_X$ (in $Shv(Y)$).
          - Side: $f_*$ is a functor from $Shv(X)$ to $Shv(Y)$.
        - A morphism in $R_{loc}Top$ consists of the same data, plus
          the additional condition
          - For $p\in Y$, $q\in X$, with
            $f(q)=p$. $f^{-1}\O_{Y,p}\rightarrow \O_{X,q}$ is a morphism
            of local rings.
            - So, given $\O_Y\rightarrow f_*O_X$, there exists an
              adjoint $f^{-1}\O_Y\rightarrow \O_X$.
            - Further, there exists a morphism from
              $\O_{Y,p}\rightarrow (f_*O_x)_p$.
            - Definition of $f^{-1}Shv(Y)\rightarrow Shv(X)$. Given
              $G\in Shv(Y)$, $f^{-1}G(U)=\colim_{V\superset f(U)} G(V)$
            - $f^{-1}\rightarrow f^{-1}(f_*(O_X))\rightarrow
              O_X\rightarrw O_{X,q}$ gives $\O_{Y,p}\rightarrow \O_{X,q}$
- $CRings/k^{op}\xleftrightarrow[F]{Spec} R_{loc}Top$
  - $F((X,\O_X))= \O_X(X)$
  - Theorem: $Spec$ provides a full and faithful embedding.
* Notes for 2012-01-17  - Schemes I
- Notation: Let $R$ be a unital commuative ring.
  - The unit provies a natural ring morphism $\mathbb{Z}\rightarrow R$.
  - Thus, $R$ is a $\mathbb{Z}$-algebra.
  - $CRing\cong \mathbb{Z}-Alg$
  - $\mathbb{Z}$ is initial in $\mathbb{Z}-alg$.
- Since $Aff cong CRing^{op}$, we see $Spec\mathbb{Z}$ is terminal in $Aff$.
  - $|Spec\mathbb{Z}|$ is prime numbers + generic point
  - If $R$ is an $\mathbb{F}_p$-algebra, then the natural morphism
    $Spec R\rightarrow Spec\mathbb{Z}$ factors through the prime $p$.
  - Similarly, if $R$ is characteristic $0$, then it factors through
    the generic point.
- Many times, it is necessary to work with $k-alg$ where $k$ is some
  $\mathbb{Z}$-algebra
  - $k-alg\cong \mathbb{Z}-alg_{k/}$. Will denote $k-alg^{op}$ as $Aff/k$.
  - Technically, $k-alg^{op}\cong (\mathbb{Z}-alg)^{op}=Aff_{Spec
    k}\cong Aff_k$
  - $Spec k$ is terminal in $Aff/k$
- *Definition* A scheme is an object $(X,O_X)\subet R_{loc}Top$ with
  the condition that every $p\in X$ has a neighbourhood $U_p$ with
  $(U)P,O_X|_{U_p})\cong Spec R_p$ for some $R_p\in\mathbb{Z}-alg$
  - Here $O_x|_{U_p}(V)=O_x(V)$.
  - Inherent glueing. Want explicit gluing.
  - $\{U_p\}_{p\in X$ is an open cover
- *Alternate Definition 1*
  - $(X,O_X)$ is a scheme, if there exists an open cover
    $\{U_\alpha\}$ of $X$ with
    each $(U_\alpha,O_X|_{U_\alpha})\cong Spec R_\alpha$
  - Where's the glueing?
    - Given $U_1$, $U_2$, one naturally has a diagram
      #+BEGIN_SRC latex :file dag.06.svg
        \begin{diagram}
          U_1\cup U_2&\rTo&U_2\\
          \dTo&&\dTo\\
          U_1&\rTo X
        \end{diagram}
      #+END_SRC
    - Now, suppose $U_1$ and $U_2$ cover X$. Question: Is $X\cong
      \colim(U_2\leftarrow U_1\cup U_2\rightarrow U_1}$?
    - We will write $U_1\cup U_2$ as $U_12$.
    - *Exammple* Let $A,B,C\in Set$ with $A\superset_{i_A} B\subset_{i_B} C$
      - We can glue $A$ to $C$ along $B$ by inducing an equivalence
        relation: Let $D=A \coprod C$. Let $p\in A$, $q\in C$ be
        equivalent if there exists $b\in B$ with $i_A(b)=p$ and
        $i_B(b)=q$. Then our "glued" set is $D/~$.
      - *Claim* $D/~=A\coprod_B C$.
        - Exists $A\rightarrow D/~$ and $C\rightarrow D/~$, which
          agree on $B$, so there exists a natural map $A\coprod_B
          C\rightarrow D/~$.
        - Likewise, $D/~$ has the universal property regarding maps
          that identify via the relation.
    - *Example* Given $A,B,C\in Top$ with $A\superset B \subet C$
      - Let $Y$ denote the "glude" space $|Y|=A\coprod_B C$. Topology
        on Y: $U\subset Y$ is open iff $f^{-1}(U)$ and $g^{-1}(U) are
        open (where $A\xrightarrow{f}Y$ and $C\xrightarrow{g}Y$).
      - Is this $A\coprod_B C$ in $Top$?
        - Have $A\coprod_B C\rightarrow Y$
        - Underlying sets are the same, so just need to check open sets
        - Let $U$ be open in $A\coprod_B C$, then the natural maps
          $A\rightarrow A\coprod_B C$ and $C\rightarrow A\coprod_BC$
          are continuous.
    - Is $X\cong \colim(U_2\leftarrow U_1\cup U_2\rightarrow U_1}$?
      - Yes.
        - We really need $U_1$ and $U_2$ to be open.
      - Setwise this is clear
      - We also have a morphism $Y\rightarrow X$. Let $U$ be open in
        $Y$. Then $U_1\xrightarrow{p_1} Y$ and $U_2\xrightarrow{p_2} Y$ are continuous.
      - $p_i^{-1}(U)$ is open in $U_i$
      - However, $U_i$ is open in $X$, so $U=(U_1\cap U)\cup(U_2\cap
        U)$, so $U$ is open in $X$. So $Y\rightarrow Y$ is a homeomorphism.
      - What about on structure sheaves?
      - Locally, $(Y,O_Y)$ and $(X,O_X$ look identical. So, using the
        sheaf property of $O_Y$ and $O_X$, you can show $O_Y\cong O_X$.
    - Result
      - $Sch/k$ is the full subcategory of $R_{loc}Top/Spec k$
        obtained by closing $Aff_{/k}$ by adding colimits of the form
        $\prod V_\beta\xdoublerightarrow[g]{f} \prod U_\alpha$ where
        $V_\beta and $U_\alpha$ are all affine schemes and $f$ and $g$
        are open imbeddings
      - A colimit of this form generates an equivalence relation; most
        of the time it is *not* an equivalence relation.
      - For this to be a reasonable (more controlled) construction we
        want our colimits to be equivalence relations.
      - In $Top$, if we have a diagram $\prod
        V_\beta\xrightarrow[g]{f}\prod U_\alpha$, with open
        immersion. Then we have $\coprod
        U_\alpha\xrightarrow{\epsilon} X=\colim$. Taking the fiber
        product of $\epsilon with itself, gives a morphism $\coprod
        U_\alpha\times_X\coprod U_\alpha\rightarrow X\times X$, this
        becomes an equivalence relation.
      - Further,
        #+BEGIN_SRC latex :file dag.07.svg
          \begin{diagram}
            \prod V_\beta&\rTo&\prod U_\alpha\\
            \dTo&&\dTo\\
            \prod U_\alpha&\rTo& X
          \end{diagram}
        #+END_SRC
      - Conclusion, $\prod V_\beta\rightarrow R$ should be a homeomorphism.
      - The category $Sch/k$ is a full subcategory of $R_{loc}Top/k$
        generated by diagrams
        $\prod V_\beta\xdoublerightarrow[g]{f} \prod U_\alpha$ with
        $f$ and $g$ Zariski open immersion, and $\prod V_\beta$ and
        equivalence relation.
      - Remark: connecting axioms of equivalence relation to maps
        relates Hartshrone's gluing, aka the cocycle condition.
      - Remark: If $X$ is a scheme (in our original definition) and
        $U_\alpha$ is an open affine cover, then $X=colim
        (\prod_\alpha\beta\doublerightarrow \prod U_\alpha)$
      - Question? What happens if we enlarge $Sch/k$ by adding
        colimits of similiar diagrams of schemes (not necessarily affine)
        - A: Nothing new.
        - The equivalence relation ensures $\{U_\alpha}$ is an open
          cover of  the resulting colimit. Using this, you break each
          $U_{\alpha$ into $U_{\alpha\gamma}$ where each
          $U_{\alpha\gamma}$ is affine. This provides an open affine
          cover of $X$. Then one just checks that this satisfied the
          equivalence relation condition.
      - Important propery about $Sch_k$
        - $Sch_k$ is closed under fiber products and $Aff_k\subet
          Sch_k$ is closed under fiber products as well.
        - But, $Aff_k$ is not closed under pushout.
        - The fiber product in $Aff/k$ is the pushout in $k-alg$. This
          is better known as the tensor product.
      - Given $(X,O_X)\xrightarrow{f} (Spec A,O_{Spec A}$ in $Sch_k$ is
        fully determined by $O_X(X)\leftarrow A$
        - $X=colim U_{\alpha\beta}\doublerightarrow U_\alpha$, where
          $U_\alpha$ is a Zariski affine open cover
        - $f$ is equivalent to a diagram
          #+BEGIN_SRC latex :file dag.08.svg
            \begin{diagram}
              Spec k_{\alpha\beta}&=&U_{\alpha\beta}\\
              &&\dTo&\drTo&\\
              Spec k_\alpha&=&U_\alpha&\rTo&Spec A
            \end{diagram}
          #+END_SRC
* Notes for 2012-01-19
- Yoneda Lemma
  - Given $C$ a category
  - Contravriant
    - The asssignment $X\mapsto h_X\in Fun(C^{op},Set)$, $h_X:Y\mapsto
      Hom (Y,X)$
      extends to a fully faithful functor $C\rightarrow Fun(C^{op}, Set).
    - Given any $H\in Fun(C^{op}, Set)$, the set of natural
      transformations $$Hom(h_X, H)\cong H(X)$.
  - Covariant
    - The asssignment $X\mapsto h_X\in Fun(C,Set)$, $h_X:Y\mapsto
      Hom (X,Y)$
      extends to a fully faithful functor $C\rightarrow Fun(C, Set).
    - Given any $H\in Fun(C, Set)$, the set of natural
      transformations $$Hom(H,h_X)\cong H(X)$.
  - Sketch of Proof
    - Given $f\in Hom(h_x, H)$, we need to give an element of $H(X)$.
      - $id\in Hom(X,X)=h_X(X)$, $f_*(id)\in H(X)$
    - Given $p\in H(X)$
      - $f:h_x\rightarrow H$ will assign $id\mapsto p
  - ...
- Introduction to Grothendieck Topology
  - *Example*
    - Let $X$ be a scheme and $Y=Spec A$.
    - We should $Hom_(Sch/k)(X,Y)\cing Hom_{k-alg}(A,\O_X(X))$
    - We proved this via a descent argument
      - We find an open (affine) cover of $X$.
        - (assume the every intersection of affines is affine in X)
      - Now, $f:X\rightarrow Y$ iduces two diagrams
        #+BEGIN_SRC latex :file dag.09.svg
          \begin{diagram}
            \coprod U_{\alpha\beta}\\
            \dTo^{i_\alpha&\rdTo(2,4)^{g'}\\
            \coprod U_\alpha\\
            \dTo^\epsilon\\
            X&\rTo^f&Y
          \end{diagram}
        #+END_SRC
        #+BEGIN_SRC latex :file dag.10.svg
          \begin{diagram}
            \coprod U_{\alpha\beta}\\
            \dTo^{i_\beta&\rdTo(2,4)^{g}\\
            \coprod U_\alpha\\
            \dTo^\epsilon\\
            X&\rTo^f&Y
          \end{diagram}
        #+END_SRC
      - Further, since $X=\colim(\coprod
        U_{\alpha\beta}\doublerightarrow \coprod U_\alpha)$ then any
        pair of such diagrams yields a morphism $X\rightarrow Y$
      - Given any $Y\in Sch/k$, for any $X\in Sch_k$ and any open
        covering $U_\alpha$ of $X$, then $Hom(X,Y)$ is the equualizer
        of the diagram
        $$\prod Hom(U_\alpha, Y)\doublerightarrow \prod
        Hom(U_{\alpha\beta}, Y)$$
      - This condition is a condition on $Hom(-,Y)$. These conditions
        go by the name *sheaf*.
      - Explicitly $h_Y=Hom(-,Y)$ is a sheaf in the Zariski topology.
      - Not every $f\in Fun(Sch_k^{op}, Set)$ is a sheaf!
      - *Example* Let $LB:Sch_k^{op}\rightarrow Set$
        - $LB(X)$ is the set of line bundles up to isomorphism on X$
        - *Claim* $LB$ is not a sheaf.
          - Let $L$ and LB$ be two non-isomorphic line bundles in $LB(X)$.
            - $LB(\mathbb{P}^1)=\mathbb{Z}$
          - Let $U_\alpha$ and $V_\beta$ be the trivializing (Zariski)
            open covers of $L$ and $L'$, respectively.
          - Let $O_X$ denote the trivial bundle.
          - $$\prod U_\alpha\xrightarrow{\epsilon}X\qquad \prod V_\beta\xrightarrow{\epsilon'}X$$
          - $\epsilon^*(L)=\O_{\prod U_\alpha}$ and
            $\epsilon'^*(L')=\O_{\prod V_\beta$
          - I can refine these two covers to $W_\gamma$ so that
          - $\prod U_\alpha\xrightarrow{\delta}$
            gives $$\delta^*L=\delta^*L'=O_{\corpod W_\gamma}$
          - $LB=\pi_0Pic$
      - Yoneda: $Sch/k\rightarrow Fun(Sch_{/k}^{op}, Set)$ functors
        through $Shv^{Zar}_k$.
      - Our example of a Grothendieck site on a category: the "big"
        Zariski site
        - $Sch_k$ + for each $X\in Sch/k$ a grouping of
          $\{U_\alpha\rightarrow X\}$ designated as covers of $X$.
        - $\{U_\alpha\rightarrow X}$ is a covering in $Sch^{Zar}_{/k}$
          iff $\{U_\alpha}$ forms a Zariski open cover of $X$.
        - A sheaf in $Sch^{Zar}_/K$ is a functor $Sch_{/k}^{op}\rightarrow
          Sets$ such that
          $$F(X)=\lim( \prod F(U_\alpha}\doublerightarrow \prod
          F(U_\alpha\times_{X} U_beta))$$
      - Let $X\in Sch/k$ and $X=U_1\cup U_2$. ($U_1$ and $U_2$ forms a cover.
        - Know
          #+BEGIN_SRC latex :file dag.10.svg
            \begin{diagram}
              U_1\times_{X}U_2\SEpbk&\rTo&U_2 \\
              \dTo&&\dTo\\
              U_1&\rTo&X
            \end{diagram}
          #+END_SRC
        - Question: Is
          #+BEGIN_SRC latex :file dag.11.svg
            \begin{diagram}
              h_{U_1\times_{X}U_2}\SEpbk&\rTo&h_{U_2} \\
              \dTo&&\dTo\\
              h_{U_1}&\rTo&h_X
            \end{diagram}
          #+END_SRC
          a pullback?
          - No. Use $LB$ for example.
        - Lesson learned, we need to e taking this colimit in sheaves.
        - Ask same question, but where colimit is a sheaf.
          - What is a colimit?
            - $F=colim(U_1\leftarrow U_1\cap U_2 \rightarrow U_2)$
              if it represents the functor
              $G\mapsto Hom(U_1,G)\coprod_{Hom(U_1\cap U_2, G),-}Hom(U_2, G)$
              (this is in $Fun(Sch^{op}_{/k},Set)$).
            - It is clear that $h_X$ will represent this.
  - To functors!
    - We have seen that we can build interesting geometric objects
      closing $Aff/k$ in $R_{loc}Top$ by certain "glueing" colimits
    - By Yoneda, $R_{loc}Top$ isn't the only category that $Aff/k$
      sits in as a full subcategory.
      #+BEGIN_SRC latex :file dag.12.svg
        \begin{diagram}
          Sch/k&\rTo^H&Fun(Sch/k^{op}, Set)\\
          \uInto&&\dTo_{\text{restriction}}\\
          Aff/k&\rTo&fun(Aff/k^{op}, Set)
        \end{diagram}
      #+END_SRC
      - Gives $Sch/k\rightarrow Fun(Aff/k^{op},Set)
        - What properties does this have?
        - What happens if we glue in $Fun(Aff^{op}_{/k}, Set)$
        - $Aff^{op}_{/k}\cong k-alg$
        - Really were embedding $Sch/k\rightarrow Fun(k-alg, Set)$
  - 1st goal
    - What geometry can we obtain/impose on a morphism of functors
      $F\rightarrow G$?
    - If $X$=Spec A\times_{Spec B}Spec C$, is $h_X=H_{Spec A}\times
      _{h_{Spec B}}h_{Spec C}$?
      - Yes
      - Let $G=h_A\times_{h_B}h_C$, then
        $$Hom(F,G)=Hom(F,h_A)\times_{Hom(F,h_B)}Hom(F,h_C)$$
      - $h_X$ represents the functor
        $$Spec D\mapsto Hom(Spec D, Spec A)\times_{Hom(Spec D, Spec
        B)} Hom(Spec D, Spec C)$$
      - Yoneda says these functors are equivalent if $F$ is of the
        form $Spec D\in Aff/k$.
      - To understand $G$ we need only give $G(Spec D)$ restricted to
        $F=Spec D$.
      - The yoneda embedding preserves fiber products.
* Notes for 2012-01-24
- We found
  - $h:Aff/k\rightarrow Fun(Aff/k, Set)$ is fully faithful and
    preserves fiber products
  - $h$ does *not* preserve pushouts
- Setup
  - Let $U$ and $Z$ be open (closed) affine subschemes of an affine
    scheme $X$.
  - Then given any two distinct morphisms $f,g:Y\rightarrow U$,
    composition with $U\hookrightarrow X$ preserves the "distinctness"
    of $f$ and $g
    - This is obvious on the topological level.
    - For sheaves
      $$f^*\O_Y\xdoublelftarrow[g]{f}\O_X$$
      - By construction,
        $$f^*\O_Y\xdoublelftarrow\epsilon_*\O_U\leftarrow \O_X$$
      - If $X=Spec R$, then $U=Spec S$ with $S$ a localization of R.
      - The construction of $r,r^{-1}\in S$ really means that $r$ has
        to go to a unit and $r^{-1}$ is the inverse of that unit.
      - Thus, a morphism on $R$ is determines and is determined by a
        morphism on $S$.
  - Same statement holds for $Z\subset X$
  - Given
    #+BEGIN_SRC latex :file dag.13.svg
      \begin{diagram}
        &&U\\
        &&\dTo\\
        Y&\rTo_h&X
      \end{diagram}
    #+END_SRC
    with $Y$ any scheme, then $Y\times_X U=h^{-1}(U)$ is a Zariski
    open subscheme of $Y$.
  - Suppose further that $Y$ is affine and the inclusion has the
    property that $X\times_X U$ is affine.
  - We can run this argument in reverse, i.e.
    - This property holds implies that $U$ is Zariski open
      - Choose the $Y$'s to be an open affine cover of
        $X$. Reconstruct $U$ as $\bigcup U\cap U_\alpha$
- With this motivation, let us define ...
  - Let $F, G\in Fun(k-\alg, Set)$
  - We say that a morphism $\eta:F\rightarrow G$ is a monomorphism (or $F$
    is a subfunctor of $G$) if $\eta_X:F(X)\rightarrow G(X)$ is a n
    inclusion of sets.
  - An epi differs depending on what category we look at:
    $Shv_Zar\subset Fun(k-alg, Set)$
  - An epimorphism of sheaves is a morphism $\eta:F\rightarrow G$ s.t.
    - For any $\phi\in G(Spec A)$, there exists an affine cover
      $U_\alpha$ of $Spec A$ such that we get a commutative diagram
      #+BEGIN_SRC latex :file dag.14.svg
        \begin{diagram}
          \prod F(U_\alpha)&\rTo&\prod G(U_\alpha)\\
          \uTo&&\uTo\\
          F(Spec A)&\rTo_{\eta_*}&G(Spec A)
        \end{diagram}
      #+END_SRC
      and a $\psi\in\prod F(U_\alpha)$, s.t. $(\prod
      \eta_{U_\alpha})(\psi)=\prod (G|_\alpha)\phi$
    - Example
      #+BEGIN_SRC latex :file dag.16.svg
        \begin{diagram}
          \coprod Y\times_XU_\alpha&\rTo&\coprod U_\alpha\\
          \dTo&&\dTo\\
          Y&\rTo&X
        \end{diagram}
      #+END_SRC
      The covering need to get $f\in h_X(Y)$ is just $\{U_\alpha\times_XY\}$
- *Definition*
  - $F\in Shv_{Zar}$ is a $-1$-scheme if it is representable
    (i.e. $F\simeq h_{Spec A}$, for some $A\in k-alg$)
  - A morphism $F\rightarrow G$ is $-1$-representable if for any
    affine scheme $Spec A$, and morphism $Spec A\rightarrow G$
    #+BEGIN_SRC latex :file dag.17.svg
      \begin{diagram}
        F\times_G Spec A&\rTo&F\\
        \dTo&&\dTo\\
        Spec A&\rTo&G
      \end{diagram}
    #+END_SRC
    $F\times_GSpec A is affine ($-1$-representable)
  - $F$ is a 0-scheme if
    1) there exists an epi $\coprod
       h_{A_\alpha}\xrightarrow{\epsilon}F$ satisfying
       - Each $h_{A_\alpha}$ is representable
       - The morphism from $h_{A_\alpha}\rightaarrow F$ is
         $-1$-representable
  - A Zariski immersion, in other words, for any $Spec B\rightarrow
    F$, the fiber morphism is a Zariski open inclusion
  - If $0$-shemes denotes the subcategory of $Fun(k-alg, Set)$ with
    objects $0$-schemes, does the natural morphism $Sch/k\rightarrow
    Fun(k-alg, Set)$ factor through a $0$-scheme.
    - No. Let $X$ be a scheme, $U_1$ and $U_2$ two open affine schemes
      - Condition 1 says $U_1\times_{h_X}U_2$ is affine = $h_{U_1\cap
        U_2}$
  - *Definition* A morphisn $F\rightarrow G$ is $0-representable if
    for $h_A\rightarrow G$, $h_A\times_G F$ is a $0$-scheme
  - $F$ is a 1-scheme, if
    - there exists an epi $\coprod h_{A_\alpha}\rightarrow F$ s.t.
      - each $h_{A_\alpha}$ is representable
      - the pullback morphism is a zariski open immersion.
  - A morphism $U_\alpha\rightarrow H_A$ where $U_\alpha$ is a
    $0-scheme and $h_A$ is a $-1$-sehcme is a Zariski open immersion
    if there exists an atlas $\{V_\beta\rightarrow U_\alpha\}_\beta$
    with composition $V_\beta\rightarrow U_\alpha\rightarrow h_A$ a
    Zariski open immersion.
  - We can repeat this indefinitely, *but* this is the last
    non-trivial enlargement.
  - 3 categories $0-schemes, $-1$-schemes, $1$-schemes
    - *Proposition*
      #+BEGIN_SRC latex :file dag.18.svg
        \begin{diagram}
          Sch/k&\rTo^h&Fun(Sch/k^{op},Set)\\
          \uInto&\rdTo&\dTo\\
          Aff/k&\rTo^{h}&Fun(Aff_{/k}^{op},Set)
        \end{diagram}
      #+END_SRC
      - The functor $Sch/k\rightarrow Fun(Aff_{/k}^{op},Set)$ is fully faithful
      - The image of $Sch_{/k}$ is equivalent to $1-Sch$
    - Proof
      - Let $X$ be a $1-Scheme and let $U_\alpha\rightarrow X$ be an atlas
      - We claim $X\cong \colim (\coprod
        U_\alpha\times_XU\beta\doublerightarrow \prod
        U_\alpha)\exiling Y$
      - First, we get a morphism $Y\rightarrow X$ which we claim is a monomorphism
* Notes for 2012-01-26
- $\eta:F\rightarrow G = Hom_{Set_{Aff}}(F,G)$ then $\eta$ is Zariski
  open immersion if it is $-11$-rep &
  the natural morphism $F\times_G h_a\rightarrow h_a$ is a Zariski
  open immersion.
- $\eta$ is $n$-representable if $F\times_G h_A$ is a $n$-scheme
- $\eta$ is a Zariski open immersion if $F\times_G h_A$ has an atlas
  $\{h_{\beta\alpha}\rightarrow F\times_G h_A\}$
  st. $h_{\beta_A}\rightarrow F\times_G h_a\rightarrow h_a$ is a
  Zariski open immersion.
- Theorem*
  - TFAE
    1) F is a $n$-scheme
    2) $F\cong|X_1\xdoublerightarrow[g]{f}X_0$ with $X_1$ and $X_0$
       disjoint unions of $n-1$ schemes and $f$ a Zariski open isomorphism
  - (1=>2) Let $X_*=\{H_{A_\alpha}\rightarrow F\}$ be an atlas for
    $F$. So, $h_{A_\alpha}\rightarrow F$ is $n-1$ representable =>
    $X_0\coprod h_{A_\alpha}$ and $X_1=\coprod H_{A_\alpha}\times F
    h_{A_\beta}$
    - For explicit, non-reducible example, set $n=0$.
    - *Lemma* $F\superset|X_1\doublerightarrow X_0|$ in $Shv$
      - Easily shown in set. We have a model for
        $|X_1\doublerightarrow X|=_{Set_{Aff}}Y'$
      - Then $Y'(Spec B)=|X_1(Spec B)\doublerightarrow X_0(Spec B)|_{Set}$
      - One can easily show that $Y'\ne Y$ in $Set_{Aff/k}$
      - What is true?
        - Sheafification $+:F\mapsto F^+$
        - $Hom_{Set_{Aff}(F, G)= Hom_{Shv)(F^+, G)$ when $G$ is a sheaf.
        - Applying this to $Y'$ we see $(Y')^+)\cong Y$.
      - Since $F\in Set_{Aff/k}$, our model for $Y'$ implies
        $Y'\subset F$.
      - This implies that $Y'$ is separated, so $+$ only add elements
        to $Y'$
      - $X_0\rightarrow Y'\subset F$. $X_0\rightarrow F$ is an epi (in
        Shv). So by explicit calculation, $(Y')^+\rightarrow F$ will
        be an equivalence.
  - (2=>1)
    - $X_*$ is an $n-1$ scheme, thus has an atlas
      $h_{A_\alpha}\rightarrow X}$.
    - *Lemma*
      1) Composition of $n-1$ representable morphisms are $n-1$ representable
      2) Composition of Zariski open morphisms are Zariski open.
    - We must show $A_\alpha\rightarrow F$ is $n-1$-rep and Zariski open.
      - Let $h_C\rightarrow F$ be a morphism
        #+BEGIN_SRC latex :file dag.19.svg
          \begin{diagram}
            G&\rTo&X_0\\
            \dTo_\eta&&\dTo\\
            h_C&\rTo&F$
          \end{diagram}
        #+END_SRC
        We must show $G$ is a $n-1$ scheme and $\eta is Zariski open
      - $X_0\rightarrow F$ is an epi (by construction), so there
        exists a Zariski open cover $\{h_{C_i}\rightarrow h_C\}$ such
        that we get a diagram
        #+BEGIN_SRC latex :file dag.20.svg
          \begin{diagram}
            &&&&X_0\\
            &&&\ru(4,2)&\dTo\\
            \coprod H_{C_i}&\rTo&h_C&\rTo&F
          \end{diagram}
        #+END_SRC
      - *Lemma* $G\rightarrow h_C$ is $n-1$ representable and has
        cover such that composition is Zariski open if we can find an
        open cover of $h_C$ such that $h_{C_j}\times
        {h_{C}}\rightarrow h_C$ satisfies this property.
      - From lemma, we can replace $h_C$ by $h_{C_j}$ and assume our
        morphism $h_C\rightarrow F$ factors through $X_0\rightarrow F$
      - In this case, $G=h_C\times_F X_0=h_C\times_{X_0}X_0\times_F
        X_0\cong h_C\times_{X_0}X_1$
      - $G$ is $n-1$ scheme and has a cover that gives a Zariski open immersion
    - Corollary
      - $1$-schemes are obtained by gluing 0-schemes.
      - $0$-schems are obtained by gluing "affine" schemes along
        affine subschemes?
    - Theorem
      - $Sch/k\rightarrow Set_{Aff/k}$ is a fully faithful subcategory
        whose essential image is the union of $n$-schemes
      - A $n$-scheme is a $1$-scheme
      - Claim: $Sch/k\rightarrow Shv_{Aff/k}$ preserves colimits
      - We found that *any* scheme $X\cong|X_1\doublerightarrow X_0$
        where $X_1$ is a disjoint union of open subschemes of elements
        - $X_0$ is a disjoint union of affine scheme and $X_1$ is a
          disjoint union of open subschemes of these affine subschemes
      - Claim: If $U$ is a Zariski open subscheme of $Spec A$ then
        $h_U$ is a 0-subscheme of $h_{Spec A}$.
      - Theses condition then show $h_X$ is a $1$-scheme
      - In particular, image of $Shv_k$ is contained  in $1$-scheme.
      - Applying this in reverse, if $X$ is a 0-scheme, then
        $X=|\coprod H_{A_\beta}\doublerightarrow \coprod
        H_{A_\alpha}|_{Shv}$ and $\tilde X=|\coprod
        H_{A_\beta}\doublerightarrow \coprod H_{A_\alpha}|_{Sch} is a
        scheme. Further, $h_{\tilde X}\cong X$.
      - 0-scheme \subset im Sch/k \subset 1-scheme
      - Apply again to get $1-scheme\subset Shv/k$
- Claim
  - $Sch/k\rightarrow Shv_{Aff/k}$ preserves colimimts
  - Exists a right adjoint to the inclusion, so preserves colimtis
  - We have an explicit formula for our colimits in both directions
* Notes for 2012-01-31
** Grothendieck Topologies
- Definition
  - Let $C$ be a category and $c\in C$.
  - A *sieve on $C$ is a subfunctor $F\subset h_c$.
  - Alternatively, a sieve $F$ on $c$ is a subcategory of $C/c$,
    satisfying $f:d\rightarrow c\in F$ and $g:d'\rightarrow d$, then
    $fg\in F$.
  - Examples
    - Let $C=Aff/k$. And any $\{U_\alpha \rightarrow X\}$ a Zariski
      covering. Then $h_{U_\alpha}\rigghtarrow h_X$ is a
      monomorphism. $h_{U_\alpha}$ is a sieve.
    - $F\subset h_X$ given by $f\in F(Y)$ if $f$ factors through
      $\coprod U_{\alpha}$.
- Definition
  - A grothendieck topology on $C$ is a collection of sieves $Cov(c)$
    for each $c\in C$, satisfying
    - $h_c$ is in $Cov(c)$
    - $F$ a covering sieve of $c$ and $b\rightarrow C$ any morphisms,
      then $G=h_b\times_{h_c}F$ is a covering sieve of $b$
    - If $S$ is a covering sieve for $c$ and $R$ is any sieve on $c$,
      and for all $f:d\rightarrow c\in S$, $h_d\times{h_C}R$ is a
      covering sieve for $d$, then $R$ is a covering sieve for $c$.
- Definition
  - A grothendieck pretopology is a collection $B(c)$ (for every $c\in
    C$) of subsets of $C/c$ s.t.
    - $\{c\rightarrow c\}\in B(c)$
    - If $\{f_i:c_i\rightarrow c\}\in B(c)$ and $g:d\rightarrow c$,
      then $\{g^*f_i\}$ is in $B(d)$
    - If $\{f_i:c_i\rightarrow c\}$ in $B(c)$ and
      $\{g_{ij}:d_{ij}\rightarrow c_i\}\in B(c_i)$, then
      $\{f_ig_{ij}\}\in B(c)$.
  - A pretopology generates a topology, by setting $F\in Cov(c)$, if
    there exists an $R\in B(c)$ s.t. $R\subset F$.
  - Examples of pretopologies
    - $C=Sch/k$, $F\in B(c)$ if $F=\{U_\alpha\rightarrow c\}$ with
      $U_\alpha$ affine and $\coprod U_\alpha$ covers $c$ and
      $U_\alpha$ Zariski open
    - $C=Top$, $B(c)$ collection of open covers
    - Alt topology on $Sch/k$, $B(X)$ collection of Zariski open covers
  - Sheaves: $F\in Set_C$ is a sheaf if, for any $S\in Cov(c)$,
    $Hom(S,F)=Hom(h_c, F)=F(c)$
  - Incredibly useful fact: Being a sheaf depends on a pretopology,
    not the topology:
    - $F$ is a sheaf iff given a pretopology on $C$ generating our
      topology, and $\{U_\alpha\rightarrow C\}\in B(c)$, then
      $$ \prod F(U_\alpha\times_c U_\beta)\twoleftarrows\prod
      F(U_\alpha)\leftarrow F(c)$$ is a limit diagram.
  - Denote the full subcategory of $Set_C$ consitying of sheaves on a
    topology $~$ as $Shv_{C,~}\subset Set_C$.
- Definition
  - A category $D$ is a grothendieck topos if $D\cong Shv_{C,~}$, for
    some $(C,~)$
  - Most common/useful example of a category with a pretopology, for
    $X\in
- Proposition (Giraud's Theorem)
  - Let $C$ be a category. TFAE
    - The category is a Grothendiect topos
    - $C$ is a equivalent to a left exact localization of $Set_D$ for
      some $D$
    - Giraud's axioms are satisfied
      - The category is presentable (has small colimits and a set of generators)
      - colimits are universal
      - coproducts are disjoint
      - equivalence rlations are effective
  - A left exact localization of $C$ is a full and faithful embedding
    $D\subset C$ with a left adjoint to inclusion $+$. This left
    adjoin preserves limits)
    - Example: $++:Fun_{Ouv(X)}\rightarrow Shv_X$
  - presentable: means that small categories are too small
    - having a "small" set of generators that generate the category
      off small colimits has the best of both worlds
    - Definition
      - A set $D$ generates a category if for any parallel morphisms
        $c_0\rightarrow C_1$ in $C$, there exists $d\in D$ with
        $d\rightarrow c_0$ that distinguishes them.
      - Immediate consequence: $C\rightarrow Set_D$ is faithful
      - Implies that $C$ will have all small limits
  - colimits are universal:
    - since $C$ has all small limits, it has fiber products
    - Definition: If $f:d\rightarow c$, then $f^*:C/c\rightarrow C/d$ preserves
      all small colimits
  - coproducts are disjoint: $Y\times_{Y\coprod Z} Z=\emptyset$
  - Every equivalence relation is effective:
    - Definition: $x\in C$, $R$ is an equivalence relation if there
      exists $R\rightarrow X\times X$, s.t. $Hom(S,R)\rightarrow
      Hom(S,X)\times Hom(S,X)$ is an equivalence relation for every $S$.
    - $R$ is effective if $R\cong X\times_{X/R}X$. ($X/R\cong
      X\coprod_R X$)
- Definition
  - A geometric morphism $F:X\rightarrow Y$ ($X$,$Y$ topoi) is a pair
    $(f^*,f_*)$ of adjoint functors, with $f^*:Y\rightarrow X$ left
    adjoint to $f_*$ and $f^* preserves finite limits.
  - Example
    - $Shv_X=Shv_{Ouv(X)}$
    - $X\rightarrow Y\in Hom_{Top}(X,Y)$
    - $Ouv_X\leftarrow Ouv_Y$
    - $Set_{Ouv_X}\rightarrow Set_{Ouv_Y}$
    - $F\in Set_{Ouv_X}\rightarrow f_*F(U)=F(f^{-1}(U))$
  - This motivates Grothendiecks definition of a point.
    - A point is a geometric morphism from $Set$
* Notes for 2012-02-02
- Missing
* Notes for 2012-02-07
- ...
- $f^*$ restricts to a functor from $Ouv(Y)\rightarrow Ouv(X)$
- Denote $Topoi\rightarrow Top:X\mapsto\{\text{points of }X\}$
  (i.e. geometric morphisms from set.
  - Let $p$ be a point of $X$: ($Set\leftrightarrows X$
  - We know $Ouv(X)\xrightarrow{p^*}Ouv(Set)$
  - Given $U\in Ouv(X)$, $\overline{U}$ is points of $X$ s.t. $p^*U=1$
  - Does this form a topology (in the classical sense) on points of $X$?
    - Yes
    - $\overline{U}\cap\overline{V}$ open?
      - $\overline{U}\cap\overline{V}=\overline{U\times_{\mathbb{1}}V$
    - $\overline{V}=\bigcup\overline{U_\alpha}$ open?
      - Set $V$ to the smallest subobject of $\mathbb{1}$ containing
        all $U_\alpha$
  - We have a functor $X\mapsto \overline{X}\in Top$
    - Given $X\rightarrow Y$
    - Do we get a morphism $pt X\rigtharrow pt Y$?
      - $Set\leftrightarrwos X\leftrightarrows Y)$
    - Verification that it is continous amounts to the fact that
      $Ouv(Y)$ maps to $Ouv(X)$
- Proposition
  - $X\cong \overline{Shv_X}$ iff $X$ is *sober*
  - $X\cong Shv_{\overline{X}}$ iff $X$ is localic and has enough points.
  - Recall
    - $X$ is *sober* if it has a unique generic point associated to
      every irreducible closed subset.
  - $pt(X)\hookrightarrow pt(Shv_X)$
    - This is continous, $X\rightarrow \overline(Shv_X}$ is continuous.
    - Why? We can recover open sets of $X$ as subobjects of $\mathbb{1}$
    - Technically, by construction, the topology on $X$ is the
      subspace topology induced from $X\hookrightarrow \overline{Shv_X}$
    - Let $p\in \overline{Shv_X}$, $p\nin X$. Let $V_p$ be the largest
      open set not containing $p$. Then $\overline{Shv_X}\setminus
      V_p=\overline{p}$. $g^{-1}(V_p$ is open and
      $\overline{Z_p}=g^{-1}(\overline{Shv_X}\setminus V_p)$ is
      closed. $X$ has a unique point whose closure is $\overline{Z_p}$.
    - Suppose $\overline{V_p}$ was reducible. Then there exists two
      closed subsets $V_1$ and $V_2$ of $X$, with $V_1\cup V_2=\overline{V_p}$.
    - Check that the point $q\inX$
      s.t. $\overline{q}=\overline{Z_p}$. Write out explicitly the
      geometric point corresponding to $q$. This will induce the same
      map $Ouv(X)\rightarrow Ouv(Set)$ as $p$.
  - $X$ is localic if $X$ is generated by subobjects of the terminal object.
    - $Ouv(X)\subset X$,
      #+BEGIN_SRC latex :file dag.21.svg
        \begin{diagram}
          X&\rTo&Fun(X^{op},Set}\\
          \uTo&\rdTo\luTo& \dTo\\
          Ouv(X)&\rTo&Fun(Ouv(X)^{op}, Set)
        \end{diagram}
      #+END_SRC
    - There is a map $Fun(Ouv(X)^{op}, Set)\rightarrow X$.
    - Denote $X_O=Ouv(X)$. Let $F\in Fun(X^{op}_O, Set)$. Then $F\cong
      colim(X/F\rightarrow Fun(X^{op}_O, Set))$ Let $\tilde F=colim(X/F\rightarrow
      X\rightarrow X)$.
    - $X_0$ has a natural (Grothendieck) topology from being a full
      subcategory of $X$.
    - We actually have $X\leftrightarrows Shv_{X_O}$.
    - Need to show that $Ouv(\overline{X})\doubleheadedleftarrow X_O$.
      - $X$ *has enough points* if $F\xrightarrow{f} G\in Hom_X(F,G)$
        is an equivalence iff $p^*f$ is for all points.
      - Easier: $X$ has enough points if given $U$, $V$ in $X_O$ with
        $U\ne V$, there exists a point s.t $p^*U\ne p^*V$.
      - Now, given $U$, $V$, with $U\ne V$; if $\overline{U}$,
        $\overline{V}$, $X$ have enough points, then there exists
        $p\in \overline U$ by $p\nin\overline{V}$. So
        $Ouv(X)\hookrightarrow Ouv(\overline(X)$)$. So $Ouv(X)\cong
        Ouv(\overline X)$ implies $Shv_{Ouv(\overline{X})cong
        Shv_{Ouv(X)}\cong X$.
    - A schme is a ringed topos $(X,\O_X)$ s.t. there exists
      $\{U_\alpha\rightarrow\mathbb{1}\}$ s.t. $X/U_\alpha\cong
      Shv_{Spec A, Zer}$ and $\coprod U_\alpha\doubleheadedrightarrow
          \mathbb{1}$ and $\O_X|_{X|_{\O_X}}\cong \O_{Spec A}$.
      - $\O_X\in X$, $h_{\O_X}: X^{op}\rightarrow CRings\rightarrow Set$
      - $X/U_\alpha\xrightarrow{F} X\xrightarrow{h_{\O_X}CRings
        - composition gives $F^*\O_X\in Fun(X/U_\alpha, CRings)$
        - $F^*\O_X$ will naturally be a sheaf on $X/U_\alpha. Write
          $F^*\O_X=\O_X|_{U_\alpha}$.
      - Check
        - $X$ is a scheme implies $X$ is localic
        - $X$ has enough points
      - $Clear: $(X, \O_X)$ a scheme in ringed top, then
        $(Shv_X,\O_X)$ is a scheme in ringed topoi.
        - If $V_\alpha\rightarrow X$ is a covering of $X$ then
          $\coprod h_{V_\alpha\rightarrow H_X=*$ is
          epi. $Shv_{X/V_\alpha}\cong Shv_{V_\alpha}$
      - $Ouv(\mathbb{1})$ generates, if for any 2 parallel arrows,
        $f,g:F\rightarrow G$ with $f\ne g$ there exists a $V\in
        Ouv(\mathbb{1}$ and a morphisms $V\xrightarrow{i} F$
        s.t. $fi\ne gi$.


* Notes for 2012-02-09
- Étale Topos of a scheme and Deligne-Mumford stacks
- Example from topology
  - Let $X$ be a (smooth) manifold
  - Enlarge $Ouv(X)$ by adding $Y\xrightarrow{f}X$ s.t. $f$ induces a
    local homeomorphism.
  - $Ouv_{ét}(X)$
    - objects $Y\rightarrow X$ s.t. $f$ is a local homeomorphism
    - morphisms - local homeomrophisms
    - $\coprod_n X\rightarrow X$ is in $Ouv_{ét}$, so is not a poset
    - Define the grothendieck topology on $Ouv_{ét}$ by saying a
      collection ${Y_\alpha\rightarrow X}$ is a cover if for every
      $x\in X$, there is $\alpha$ s.t. $f_\alpha^{-1}(x)\ne\emptyset$
      - Check
        1) refinement of a cover is a cover.
        2) pullback of a cover is a cover
      - Follows from the fact that local homeomorphisms are closed
        under composition
    - *Claim* $Shv_{Ouv_{ét}}=Shv_X$!
      - $Ouv_{ét}\superset Ouv(X)$, so we get a restriction
        $Shv_{Ouv_{ét}}\rightarrow Shv_X$
      - *Definition* A site $(C,~)$ is sub-canonoical, if the Yoneda embedding
        $C\rightarrow Set_C$ factors through $Shv_{C,~}$.
        - If $(C,~)$ is subcanonical, then any covering in $C$ is a
          covering in the canonical topology on $Shv_{C,~}$
        - Why? Let $c\in C$ and $\{b_\alpha\rightarrow c\}$ a
          covering. We know $Hom(h_c, F)\cong F(c)$. So if $F$ is a
          sheaf, then
          $$F(c)\cong \lim \prod F(b_\alpha)\tworightarrows \prod
          F(b_\alpha\times_c b_\beta)$$
          $$Hom(h_c, F)\cong \lim \prod Hom(h_{b_\alpha},
          F)\tworightarrows\prod Hom(h_{b_\alpha}_\times_{h_c}h_{b_\beta})$$
          Thus $Hom(h_c, F)\hookrightarrow Hom(\coprod h_{b_\alpha}, F)$
          and $prod h_{b_\alpha}\doubleheadedrightarrow h_c}$. This
          proves that $\{h_{b_\alpha}\rightarrow h_c\}$ is a cover in
          the canonical topology.
      - $Ouv(X)$ and $Ouv_{ét}(X)$ are sub-canonical.
      - For any $Y\xrightarrow{f} X\in Ouv_{ét}$, there exists a
        covering $U_\alpha$ s.t. $fi_\alpha:U_\alpha\rightarrow X$ is
        in $Ouv(X)$.
      - The restriction $Ouv_{ét}\rightarrow Set_{Ouv_{ét}}\rightarrow Set_{Ouv_X}$
        is fully faithful (for the same reason $Sch\rightarrow
        Fun(Aff^{op}, Set)$. This gives a fully faithful functor
        $Ouv_{ét}(X)\rightarrow Shv_X$
      - $Shv_X\cong
        Shv_{Shv_X,can}\xrightarrow{f}Shv_{Ouv_{ét},X}\cong Shv_X$
    - Let $X$, $Y$ be in $Sch/\mathbb{C}$. with $X$ and $Y$ of finite
      type. WE have "analytic variety" $X^{an}$, $Y^{an}$. There
      exists a covering of $X$ by finite type affine schemes. An
      finite type affine scheme over $\mathbb{C}$ is a subset of
      $\mathbb{C}^n$: $R\doubleheadedleftarrow \mathbb{C}[x_1,\dotsc
      x_n\hookleftarrow I$.
      - Each $U_\alpha$ has the subspace topology from $\mathbb{C}^n$
        with analytic topology. These glue to give $X^{an}$ a
        Hausdorff topology.
        - Example $\mathbb{P}^{an}_1\cong S^2$
      - Fact: $X^{an}\rightarrow Y^{an}$ is a local diffeomorphism iff
        at every $x\in X^{an}$, $y\in Y^{an}$, $f_*:T_xX^{an}\xrightarrow{\cong}T_yY^{an}$
      - This is not true for the Zariski topology.
      - Informally, over $\mathbb{C}$, a morphism $Y\rightarrow X$
        will be étale, if after "analytification", it satisfies either
        of the above conditions.
      - The latter condition can be tested without topology.
        - *Fact* If $f^{an}$ satisfies this, then $f^*TY\cong TX$
      - We need a definition of $T^*X$ without going to $Top$
      - Kähler differntials
        - Let $Spec k\rightarrow Spec X\rightarrow Spec k$ (i.e. $X$
          is a "pointed" $k$-scheme)
        - If $X=Spec B$ is affine, then the Kähler differntials are
          $\pi_o\mathbb{L}_{B/k}$, where $\mathbb{L}_{B/K}$ is
          André-Quillen homology
        - Derivations
          - Let $B$ be a $k$-algebra and $M$ a $B$-module
          - An $M$ valued $k$-linear derivation of $B$ is a $\phi\in
            Hom_{k-mod}(B,M)$ s.t. $\phi(bb')=b\phi(b')+\phi(b)+b'$
            (not a morphism of $B$-modules)
          - Let $Der_{B/k}(M)$ be the collection of all $M$ valued derivations.
          - *Definition* The Kähler differntial $\Omega_{B/k}$ is the
            $B$ module representing $Der_{B/k}$.
- Definition
  - Let $X$ and $Y$ be $Sch$.
  - $f:X\rightarrow Y$ is *étale* if for all $x,y$ with $f(x)=y$,
    there exists $U_x=Spec B$ and $V_y=Spec B$ affines,
    s.t. $\overline{f}:=f|_{U_x}:U_x\rightarrow V_y$
    s.t. $\overline{f}^*\Omega_{B/k}\cong \Omega_{A/k}.
  - Assuming Kähler diffentials are a sheaf, $f:X\rightarrow Y$ is
    étale if $f^*(\Omega_{X/k}\rightarrow \Omega{Y/K}$ is an isomorphism.
* Notes for 2012-02-14
- Recall
  - $f:Spec B\rightarrow Spec A$ is étale iff $\Omega_{B/A}\cong 0$
    - technically, $f^*:\Omeaga_{Spec
      A/k}\xrightarrow{\cong}\Omega_{Spec B/k}$
- Alternative definition
  - $f$ is étale if it is
    1) flat
    2) unramified
  - $f$ is *flat* iff $B$ an a module
    - An $A$-module $M$ is flat if $\otimes M$ preserves exact
      sequences in $A$-mod
    - $B$ being a flat $A$-module is the algebraic geometer's version
      of a subversion.
  - $f$ is *unramified* if for any $p,q$ in $Spec B$ (resp. $Spec A$),
    with $f(p)=q$, the induced morphisms $A_q\rightarrow B_p$ of local
    rings satifies $B_p/mA_q\otimes B$ is a finite field extension
    of $A_q/mA_q$.
  - Suppose we are working over an algebraic closed field
    $Sch/k$. Then $f$ is étale iff given $Spec k\rightarrow Spec
    A\xleftarrow{f} Spec B$,
    $$Spec k\times_{Spec A}Spec A\cong \coprod Spec k$
  - Theorem: The two definitions of étale are equivalent.
  - Example: Let $A=\mathbb{C}$ then $Spec B\rightarrow Spec A$ is
    étale if $Spec B=\coprod Spec\mathbb{C}$
- Define the *little étale site* of $Spec A$ to be the category of
  étale morphisms whose codomain is $Spec A$.
  - *Example* If $U$ is a Zariski
    open subset of $Spec A$, then $U\hookrightarrow Spec A$ is étale.
    - $Ouv_{Spec A}\subet Ét_A$. Define a grothendieck pretopology
      on $Ét_A$. A covering of $Y\rightarrow Spec A$ is a collection
      of $\{Y_\alpha\rightarrow Y\}$ of étale maps s.t. every point
      in $Y$ has a lift to some $Y_\alpha$.
    - To show that this is indeed a grothendieck pretopology, we
      just need
      1) composition of étale maps are étale
         - $Spec C\xrightarrow{f} Spec B \xrightarrow{g} Spec A$ If
           $f$ and $G$ are étale, then
           $$\Omega_{Spec C/k}\cong f^*\Omega_{Spec B/k}\cong
             f^*g^*\Omega_{Spec A/k}$\cong (g\comp f)^*\Omega_{Spec A/k}$$
      2) pullbacks of étale maps are étale
  - The *étale topos* of $Spec A$ is $Shv_{Ét_A}$
    - Generally speaking $Shv_{Ét_A}$ will not be localic.
    - $Ouv_{Spec A}\hookrightarrow Ét_A$ gives $Shv_{Ét_A}\rightarrow
      Shv_{Zar, Spec A}$
    - Main difference.
      - Let $A$ be a field.
      - $Spec B\rightarrow Spec A$ is étale iff $Spec B=\coprod Spec
        K_\alpha$ with $K_\alpha$ a finite separable field extension
        of $A$.
      - $Shv_{Zar, Spec A}\cong Set \leftarrow Shv_{Ét_A}$
      - $f$ étale (and each $K_\alpha$ is normal.
        - Let $B=K$ with $K$ finite seperable over $A$
        - $Spec K\times_{Spec A}Spec K$ splits as
          $\coprod_{Gal(K/A)}Spec K$
      - Let $F$ be an étale sheaf on $Spec A$. Then
        $$F(Spec A)\cong \lim(Spec K\tworightarrows \prod F(Spec
        K\times_{Spec A}Spec K)$$.
        The splitting implies
        $$F(Spec A)\cong \lim(Spec K\xtworightarrows[id]{Gal} \prod F(Spec K)$$
        - $Shv_{Ét_A}\cong Gal(\overline{A^{sep}/A)-sets$
          ($Gal(\overline{A^{sep})$ profinte group)
- *Definition*
  - $(X,\O_X)$ (a ringed topos) is a *Deligne-Mumford stack* if there
    exists $F_\alpha$, s.t. $\coprod F_\alpha\doubleheadedrightarow
    \mathbb{1}$. and $(X/F_\alpha, \O_X|_{F_\alpha})\cong Shv_{Ét_{A_\alpha}}$.
** $\infty$-categories and quasi-categories
- Chapter 1 of Lurie's $\infty$-topoi
- Fundamental example
  - Grothendieck: $X$ topological space.
  - $\Pi_{\le0}$ set of points, up to homotopy (path components)
  - $\Pi_{\le1} X$ is a category
    - objects :: points of X
    - morphisms :: homotopy classes of paths
  - $\Pi_{le2} X$
    - objects :: points of X
    - morphisms :: parameterized paths $I\rightarrow X$
    - 2-morphims :: $Hom(\gamma,\sigma)$ ($\gamma,\sigma:I\rightarrow
                    X$) are (homotopy classes of) homotopies between
                    $\gamma$ and $\sigma$ fixing the endpoints
  - $Pi_{<\infty}X$ has as "$n$-morphisms" all homotopies between $n-1$-homotopies
  - composition of morphisms isn't associative, but is up to homotopy.
  - every morphisms is invertible up to higher morphisms.
- Grothendieck: Any reasonable definition of a higher category
  satisfying these two properties should give an equivalence with
  $\Pi_{<\infty}X$ for some $X\in Top$.
- Definition: The "category" of $(\infty,0)$-categories is $Top$.
- $\Pi_{\le1}$ and $\Pi_{\le1}Y$ Are categories, Now, suppose
  $X\rightarrow Y$ is a continuous morphism. When is the induced
  $\Pi_{\le1}X\rightarrow \Pi_{\le1}Y$ an "equivalence of categories".
  - Suppose $X$ and $Y$ are $2$-truncated (i.e. $\pi_{\ge2}$(X)=*$)
  - Conversion:
    - $\pi_0(X)\rightarrow \pi_0(Y)$ is an isomorphism
    - $\pi_1(X,x)\cong\pi_1(Y,q)$ s.t. $f(p)$ is in the same path
      component as $q$.
    - $f$ is a "weak equivalence".
- Definition
  - A $(\infty,0)$-category is $\Pi_{<\infty}X$ for some $X$ in $Top$
    and an equivalence of $(\infty,0)$-categories is a a weak
    homotopy equivalence of space.
- Recall: Category of categories is a category, but also a $2$-category
  - This points to the "category" of $(\infty,0)$-catgeory as being
    something more than just a category
  - Cat of $(\infty,0)$-cat should be a $(\infty,1)-cat
  - Points to $(\infty,0)-cat being $Top$ with natural enrichment
  - *Definition* $(\infty,0)-cat is the enriched category of
    CW-comlexes with its natural $Top$-enrichment
- *Definition* An $(\inty,1)$-category has as hom objects,
  $(\intfy,0)-categories
  - A $(\infty,1)$-category is a category enriched over topological spaces
- If we use $Sing:Top:\leftrightarrows:Set_\Delata:|\cdot|$. The nwe
  can say that an $(\infty,1)$-category is a simplicial category where
  the simplicial sets are Kan complexes
- Given a category $C$, $NC\in Set_\Delta$
- We can pick out which simplicial sets are in the image of $N$.
* Notes for 2012-02-16
- 0-cat -> Set
- 1-cat -> cat
- 2-cat -> cat enriched over categories
- $(\intfy,0)$ -> space
- $(\intfy,1)$ -> category enriched over $(\infty,0)$-category (spaces)
- Recall
  - A quasi-category will be a model for $(\infty,1)$-categories, is a
    sSet satisfying the Kan condition for $0<1<n$.
  - Let $C$ be a category, $\Lambda_2^0\rightarrow NC$ is a pair of
    morphisms $f,g$ with the same domain. Then a lift is a morphism
    $f'$ with $f'\circ f=id$.
  - If $NC$ is a Kan complex, then $C$ is a groupoid
- One advantage: $Set_\Delta$ is enriched over itself, and given a
  quasi-cat $X$, $Map(K,X)$ for any $K\in Set_\Delta$ is a quasi category.
- So $Set_\Delta$ with its natural self enrichment provides the
  $(\infty, 2)$-category of $(\infty,1)$-categories.
- To tie quasi categories to 2-cat and provide a notion of equivalence
  - $C:Set_\Delta\leftrightarrows Cat_\Delta:N$ will be an adjoint
    pair. The restriction of $N$ to $Cat$ should recover nerve.
  - *Fact* to give a colimit preserving functor from
    $Set_\Delta\rightarrow C$, it is enough to give values on the full
    subcategory $\Delta\subset Set_\Delta$.
  - $C\Delta_n$
    - $C\Delta_n=\{*\}$
    - $C\Delta_1:*\xrightarrow{*}*$
    - Recipe for $C\Delta_n$ has $n-1$ objects and $Hom(n,n+m)$ will
      be an $m-1$ cube. The vertices in the cube correspond to all
      possible compositions.
    - Lastly $N$ is the adjoint. Let $C\in Cat_\Delta$. Then
      $(NC)_n=Hom(C\Delta_n, C)$. i.e. $NC_0=ob C$, $NC_1$ is
      morphism of $C$. $NC_2$ a composable pair $(f,g)$ and a homotopy
      from $f\circ g$ to any other morphism.
    - Does $CNC=C$?
      - No, but it is weakly equivalent.
      - Recall an equivalence of simplicial categories is a morphism
        $F:C\rightarrow D$ s.t. $\pi_0F:\pi_0C\rightarrow \pi_0D$ is
        an equivalence and $f$ induces a weak equivalence on Hom's.
      - Define to $X,Y\in Set_\Delta$ to be *categorically equivalent*
        iff $C(X)=C(Y)$.
      - Inside of $Cat_\Delta$ you have the subcategory enriched over
        Kan comlexes. $N:KCat\rightarrow$quasicategories
      - If $C\in KCat_\Delta$ and every morphisms is invertable up to
        homotopy, then $NC$ is a Kan complex.
      - Our model for $(\infty,1)-cat$ will be $Kan\subset Qcat\subset
        Set_\Delta$. $Sing X$ ($X$ a topoligical space)$ is the model
        for $\Pi_{<\infty}X$.
      - *Proposition* There exists a model structure on $Set_\Delta$
        s.t. weak equivalences are "categorical equivalence" for
        quasicategories.
* Notes for 2012-02-28
- We redefine the limit in a category as the final object in a type of
  overcategory.
- $f:C\rightarrow D$, $Nf:NC\rightarrow ND$, we have $ND/NF$
- Give any morphism in $Set_\Delta$ $f:X\rightarrow Y$ we always have $Y/f$
- We are left with defining initial/terminal objects.
- Recall $Set_\Delta\xleftrightarrwos[\mathbb{C}]{N}Cat_\Delta$
  - What is a terminal object in $\mathbb{C}X$
  - 1st definition: A final object in a simplical cateegory $C$ is an
    object of $c\in C$, s.t. $Hom(c',c)=*$
  - Example: Given a ring $R$, $CH(R-mod)$ is an abelian category.
    - $(CH(R-mod,W=\text{quasi-iso})$
    - $L^wCH(R-mod)\in Cat_\Delta$
      - Given $f:F\rightarrow G$ a quasi-iso,
      - $Hom_{L^w(CH(R-mod))}(G,0)$ has (at least) two elements
        #+BEGIN_SRC latex :file dag22.svg
          \begin{diagram}
            G&\rTo&G&\rTo&0 \\
            =&&\dTo^f&&=\\
            G&\rTo&F&\rTo&0
          \end{diagram}
        #+END_SRC
      - $L^w(CH(R-mod)$ is not $*$ but is contractible.
      - Recall, $C$ a category, $c\in C$ final, then $C/c\simeq C$
  - Final definition: A final object in $C\in Cat_\Delta$ is an object
    $c\in C$ with $Hom(-,c)$ weakly equivalent to $*$.
  - Example: What property does the morphism $NC/c\rightarrow NC$ have
    if $c$ is final.
    - Claim: $c$ is final iff $NC/c\rightarrow NC$ is a trivial Kan fibration.
      - A lift in
        #+BEGIN_SRC latex :file dag23.svg
          \begin{diagram}
            \partial \Delta_n&\rTo&NC/c \\
            \dInto&\ruDashedto&\dTo \\
            \Delta_n & \rTo & NC
          \end{diagram}
        #+END_SRC
        is given by the choice of composable morphism, which is
        compatible since $N$ commutes with $-/c$.
      - Suppose $C$ is not final. Then there exists $c'\in C$
        s.t. $Hom(c', c)$ is either $\emptyset$ or has at least 2
        elements $g$ and $g'$. A lift in the diagram
        #+BEGIN_SRC latex :file dag24.svg
          \begin{diagram}
            \partial \Delta_1&\rTo^{g,g'}&NC/c \\
            \dInto&&\dTo \\
            \Delta_1 & \rTo & NC
          \end{diagram}
        #+END_SRC
        would give a map in $C$ contracting the two morphisms.
    - This suggests the following: A terminal object in a
      quasicategory $X$ is $x\in X_0$ s.t. $X/x\rightarrow X$ is a
      trivial Kan fibration.
    - *Definition* A limit of $f\in Hom_{Set_\Delta}(X, Y)$ is a choice of terminal
      object in $Y/f$.
    - Remark: In $C\in Cat$, a terminal object is well defined up to
      iso. In quasi-categories, it is well defined up to a
      contractible space.
    - $(Y/f)_0$ is an element in $Hom(\Delta_0\times X,
      Y)$. $\Dlata_0\rightarrow \Delta_0\times X$ induces
      $$Hom(\Delta_0\times X,Y)\rightarrow Hom(\Delta_0, Y)=Y_0$
    - Let $C$ be a model category. $f:D\rightarrow C^{cf}$ induces
      $D\rightarrow L^w(D)\xrightarrow{L^wF}(C^{cf})$. Taking nerves:
      $ND\rightarrow NL^w(C^{cf}$ in quasi-categories.
      - *Claim* $\lim NL^w f\simeq holim f$
- 2 Constructions: Yoneda and Adjoint Functors.
  - Yoneda: $c\rightarrow Hom(-,c)$ for $c\in C$ induces a full and
    faithful embedding.
  - Enriched Yoneda: If $c\in C\in Cat_\Delta$, $Hom(-,
    C):C^{op}\rightarrow Set_\Delta$
  - One can hope for $C\rightarrow Fun(C^{op}, Set_\Delta)$ to be an embedding.
    - $Fun(C^{op}, Set_\Delta)$ is the simplical category of
      simplicial functors
    - Technically a category, but there exists the projective model structure
    - Will right $L^wFun(C^{op}, Set_\Delta)$ as $Fun(C^{op}, Set_\Delta$
  - Brief (but important detour)
    - Recall that associated to a (pseudo-) functor $C\xrightarrow{F}Cat$ we can
      build a category $\Epsilon\rightarrow C$
      - objects of $\Epsilon=\coprod_{c\in C}obj F(c)$
      - morphisms in $\Epsilon(x,y)$, are pairs $(g,\eta)$ with $g\in
        Hom_C(\pi x, \pi y)$ and $\eta\in Hom(Ff(x), y$
    - Given $\Epsilon\rightarrow C$, when does it give a functor
      $C\rightarrow Cat$?
    - Right condition: $\Epsilon\rightarrow is a cocartesian fibration.
      - *Definition* A morphism $f:x\rightarrow y$ in $\Epsilon$ is cocartesian over
        $C$ if, given a diagram
        #+BEGIN_SRC latex :file dag25.svg
          \begin{diagram}
            &&z\\
            &\ruTo&\uDotsto \\
            x&\rTo^f& Y \\

            &&\pi z\\
            &\ruTo&\uTo \\
            \pi x&\rTo^{\pi f}& \pi Y \\
          \end{diagram}
        #+END_SRC
        there exists a lift making both diagram commute.
        (We want $f$ to lokk like the morphism $F(\pi(f))(x)$.
      - Alternative characterization, $Hom(y,z)\cong
        Hom(x,z)\times_{Hom(\pi x, \pi y)}Hom(\pi y, \pi z)$.
      - *Definition* $\Epsilon \rightarrow C$ is a cocartesian
        fibration if for every $\eta\in C$ there is a cocartesian
        morphism lifting it.
      - To assign a functor to $\pi$,
        - objects of $F(c)$ objects in $\Epsilon lifting above $c$
        - morphisms of $F(c)$, $Hom_{F(c)(e, e')\subset
          Hom_\Epsilon(e,e')$ with $\pi\eta = id_c$
      - *Prop* Given a morphism $f\in C$, any two choices of cartesian
        morphisms lifting $f$ are isomorphic
* Notes for 2012-03-01
- Why? Yoneda is not illuminating in quasi categories
- *Definition* $\Epsilon\xrightarrow{\pi}C$ is a cocartesian fibration
  if for every pair $(e,f)$, with
  #+BEGIN_SRC latex :file dag26.svg
    \begin{diagram}
      e\in\Epsilon\\
      \dTo
      \pi(e)&\rTo^f&y'
    \end{diagram}
  #+END_SRC
  there exists $\overline{f}\in Hom(e,y)$ s.t. $\pi\overline{F}=f$,
  initial among $g$, with $\pi(g)$ factoring through $f$.
- *Example* $C_{c/}\rightarrow C$ is a cocartesian fibration.
- *Example* of psuedofunctor: $K-alg \rightarrow Cat:A\mapsto A-mod$ -
  moduli stack of $K-modules$
- All these statements have a dual.
- *Theorem*fi_
  - cocartesian fibration over $C$ iff psuedofunctor
  - cartesian fibration over $C$ iff contravariant psuedofunctor
- Exists quasicategory notion of this.
  - $let $\Epsilon, X\in Set_\Delta$.
    #+BEGIN_SRC latex :file dag27.svg
      \begin{diagram}
        \Lambda^i_k&\rTo&\Epsilon\\
        \dTo&&\dTo\\
        \Delta_k&\rTo& X
      \end{diagram}
    #+END_SRC
    1) $\pi$ is a right fibration if the diagram has a lift for all
       $0<i\le k$.
    2) $\pi$ is a left fibration if the diagram has a lift for all
       $0\le i< k$.
    3) $\pi$ is a inner fibration if the diagram has a lift for all
       $0\le i\le k$.
  - a left fibration *is* a cocartesian fibration, for nerves.
- *Remark* Set $X=\Delta_0$
  - Proposition
    - $\Epsilon\xrightarrow{\pi} \Delta_0$ is an inner fibration if
      $\Epsilon$ is a quasicategory.
    - $\pi$ is a right/left fibrationff $\Epsilon$ is a Kan complex.
- Let $\pi$ be a left fibration
  #+BEGIN_SRC latex :file dag28.svg
    \begin{diagram}
      \Delta_k&\rTo&\Epsilon\times_X\Delta_0&\rTo&\Epsilon \\
      \dTo&&\dTo&&\dTo^{\pi} \\
      \Delta_k&\rTo&\Delta_0&\rTo&X
    \end{diagram}
  #+END_SRC
  $\Epsilon\times_X\Delta_0\rightarrow \Delta_0$ is a left fibration,
  so it is a kan complex.
- Want to say a left fibration is equivalent to $Fun(X, S)$.
  - Let $S=N(Kan)$ where $Kan$ is the full subcategory of kan complexes
  - *Theorem*
    - There exists a model structure on $Set_\Delta/X$ s.t. the
      fibrant and cofibrant objects are left (resp. right) fibrations
    - with this model, there exists a quillen equivalence with
      $Fun(\mathbb{C}X, Set_\Delta)$ (projective model structure.
* Notes for 2012-03-06
- $X\rightarrow S$ a left fibration <=> $\mathbb{C}S\rightarrow Kan$
- (co-)cartesian fibrations <=> $\mathbb{C}S^{op}\rightarrow
  Cat_\Delta$ ($\mathbb{C}S\rightarrow Cat_\Delta)$
- Set $S=\Delta_1$. $M\xrightarrow{f} \Delta_1$ cocartesian
  - $\mathbb{C}\Delta_1}\rightarrow Cat_\Delta$
    #+BEGIN_SRC latex :file dag29.svg
      \begin{diagram}
        C=M\times_{\Delta_1} \Lambda_1^0&\rTo&\Lambda^1 \\
        \dTo&&\dTo\\
        \Lambda_1^0&\rTo&\Delta_1
      \end{diagram}
    #+END_SRC
    #+BEGIN_SRC latex :file dag30.svg
      \begin{diagram}
        D=M\times_{\Delta_1}\Lambda_1^1&\rTo&M\\
        \dTo&&\dTo\\
        \Lambda_1^1&\rTo&\Delta_1
      \end{diagram}
    #+END_SRC
    Gives map $\mathbb{C}C\rightarrow \mathbb{C}D$. If $M$ is a
    cartesian fibration, there is $\mathbb{C}D\rightarrow\mathbb{C}C$.
  - *Claim* If $M$ is cartesian and co cartesian,then those two
    functors are adjoint.
- *Definition* An adjoint functor in quasi-cat is a cartesian
  cocartesian fibration over $\Delta_1$
- Big side example
  - Let $k$ be a commutative ring. (i.e. $k$ is a $\mathbb{Z}$-algebra)
  - There exists a natural category $K-alg$
  - $k-alg_\Delta\coloneqq Fun(\Delta^{op}, k-alg)$
  - Any category that has infinite coproducts is tensored over sets.
  - We make $k-alg$ tensored over $Set_\Delta$ levelwise.
  - General nonsense => if $C\otimes D\rightarrow D$, we can give $D$
    an enrichment over $C$.
  - Given $R_*, S_*\in k-alg$, Hom(\Delta_0\otimes R_*,S_*)$ is a set,
    $Hom(\Delta_1\otimes R_*,S_*)$ is a set.
  - Set
    $Hom(_{k-alg_{\Delta}}(R,S)_n=Hom_{k-alg_\Delta}(\Delta_n\otimes
    R, S)$.
  - Likewise, if $D$ is enriched over $C$ often means that $D$ is
    tensored and cotensored over $C$.
    - *Definition* $Hom(-\otimes X, Y)$ is a representable functor.
  - We should think of $k-alg_\Delta\in Cat_\Delta$, not $\in Cat$.
  - *Propostion* (Homotopical Algebra, Quillen)
    - $k-alg$ has a combinatorial simplicial model structure where
      weak equivalences are defined by th natural map
      $k-alg\rightarrow Set_\Delta$.
    - Side note: Can do same operation in dg.
    - Shipley:
      - $DK:Ch^{\le0}(k-alg)\leftrightarrows k-alg_\Delta:N$
      - $N$ is monoidal but *not* symmetric monoidal
  - Now: Using this model structure on $k-alg_\Delta$, apply
    $N(k-alg_\Delta^{cf})$ to get a quasicategory
  - $k-alg\rightarrow Cat:A\mapsto A-mod, (A\rightarrow
    B)\mapsto(-\otmes B)$
  - $k-alg^{op}\rightarrow Cat:A\mapsto A-mod, (A\rightarrow B)\mapsto(forget)$
  - $\tilde{QC}\xrigarrow{\pi} k-alg$. Over $A$ this is $A-mod$.
    - obj of $\tilde{QC}=\coprod_{A\in\k-alg}obj(A-mod)$
    - $Morph(P,Q)\ni(f,\epsilon)$ where $f\in Hom(\pi_1(p), \pi_1(Q))$ and
      $\epsilon:P\otimes \pi_1(Q)\rightarrow Q$
  - $\tilde{\tilde{QC}}\xrigarrow{\pi_2} k-alg$. Over $A$ this is $A-mod$.
    - $Hom(P,Q)\ni(g,\eta)$ where $g\in Hom(\pi_2 P,\pi_2 Q)$ and
      $\eta\in Hom(Q,P)$
* Notes for 2012-03-13
- *Definition* $C$ is an $\infty$-topos, if there exists an adjoint
  pair $(i:C\rightarrow P(D)=Fun(D,S):a)$, such that $i$ makes $C$ a
  full subcategory of $P(D)$, and $i$ preserves finite limits.
  - Alternative characterization, $C$ is a left exact localization of
    $P(D)$, for some $\infty$-category $D$.
- *Remark* In the case that $C, D, S=Set$, then $$C$ is a topos by
  giraud's theorem
- Connection with Jardine's theory
  - Let $(C,\tau)$ be a site. $Fun(C^{op}, Set)$ has at least 2
    important model structures
    - projective
    - Jardine's local
- Prop 5 11.1 (Lurie's $\infty$-topos)
  - $C$ a quasicategory
  - There are 3 equivalent ways of describing $P(C)$
    - $P'(C)=NP'_D(C)^{cf}$ where $P'_\Delta(C)$ is the model
      category $Set/C$ with the model structure having right fibrations
      as objects
    - $P''(C)=NP''_\Delta(C)^{cf}$, where
      $P''_\Delta(C)=Fun(\mathbb{C}C^{op}, Set_\Delta)$
    - $P(C)=Map_{Set_\Delta}(C^{op},S)$
  - $P'(C)\simeq P''(C)\simeq P(C)$
  - $P(C)$ is presheaves on $C$
  - So, knwo $N\mathbb{C}C \simeq C$. so
    $N(Fun_{Cat_\Delta}(C^{op},Sets_\Delta))\cong P(NC)$
  - So, A left localization of $Fun_{Cat_\Delta}(C,Set_\Delta)^{cf}$
    will have a left exact totalization on $P(NC)$
  - Point: If $X$ is Fun(C^{op},Set_\Delta)^{cf,-}$, then $NX$
    is a quasicategory, and will be a left exact localization of $P(NC)$.
  - In particular, $NX$ is an $\infty$-topos
- Grothendieck topologies on $C$ are in correspondence with
  grothendiect topologies on $hC$..
- If $C=ND$, $D$ an actual category, then $hND\cong D$.
- Define $Shv_{ND,~}\subset P(ND)$ as the full subcategory of $P(ND)$
  conisting of $F\in P(ND)$ s.t. $Map(c,
  F)\xrightarrow{\simeq}Map(U,F)$ (in $hP(ND)$) for any covering sieve
  $U\rightarrow h_C$.
- Facts $NX\subset Shv_{ND,~}$.
  - You can recover $NX$ from $Shv_{ND,~}$ by further localizing
    1) localize with respect to $\tilde\pi_i$
    2) look at objects that are are hyper-complete.
  - Now, let $X$ be an $\infty$-topos, and $C$ an $\infty$-category
    - A $C$-valued sheaf on $X$ is a functor $X^{op}\rightarrow C$
      that preserves limits.
  - Suppose that $C=S$. Then a space valued sheaf on $X$ is a limit
    preserving functor $X'\subset P(X)$ of space-valued sheaves
  - $X\subset Fun(X^{op}, Set$, then $F\in Fun(X^{op}, Set)$ is
    represetnable if $F$ preserves limits

- $\tilde{k-alg_\Delta}=N(k-alg_\Delta)^{cf}$. Let
  $F:X^{op}\rightarrow \tilde{k-alg}$ be limit preserving. ($F is a
  "ring valued" sheaf on $X$). Composing with
  $\tilde{k-alg)\rightarrow S$, we get back an object of $X$. This, a
  *ring-valued sheaf* is just a $x\in X$ s.t. $Hom(-,x)$ has a ring structure.
- *Definition* A ringed $\infty$-topos is a pair $(X,\O_X$ with $X$
  and $\infty$-topos and $\O_X$ a simplicial $k-alg$ valued sheaf on $X
- *Definition* A $C$-structured $\infty topos is a pair $(X,\O_X)$
  with $\O_X$ a $C$ valued sheaf on $X$.
- A $C$-structured morphism between $C$-structured topoi $(X,\O_X$ and
  $(Y,\O_Y$ is
  - a geomtric morphism $(f^*,f_*:X\rightarrow Y$
  - ${f^{*}}^{op}:Y^{op}\leftarrow X^{op}\xrightarrow{\O_X}C$ is a $C$
    valued sheaf on $X$. $\eta:\O_Y\rightarrow F_*\O_X$ in $Fun(X^{op},C)$.
* Notes for 2012-03-15
- $Shv_X(C)\subset Fun(X^{op}, C)$ where $X$ an $\infty$-topos and $C$ an $\infty$-category
- Many equivalent ways of defining "sheaf of rings" on a topos
  (classically)
  - where $X$ topological space, $C=Shv_{Ouv(X)}\cong Shv_X$.
  - $F: Ouv(X)^{op}\rightarrow CRing$
  - $F:Shv_X^{op}\rightarrow CRing$ (limit preserving)
    - $G\in Shv_X^{op}$ is $lim Ouv(X)^{op}_{G/}$
    - $G\in Shv_X\cong colim Ouv_(X)/G$
  - $\tilde F: Shv_X^{op}\rightarrow CRing$ by Freyd's adjoint functor
    theorem, there exists a $\tilde G:CRings\rightarrow Shv_X^{op}$
    with $G$ preserving colimits.
    - $G^{op}:CRings\rightarrow Shv_X$ (explicitly given by object
      representing  $R\mapsto Hom(R, F(-))$
  - $\tilde G:(CRing^{fin}^{op}\rightarrow Shv_X$ (limit preserving)
    - $CRings$ is generated (by colimits) by $CRing^{fin}$ (finitely
      presented rings)
    - $R\in CRing^{fin}$ implies $Hom(R, -)$ commutes with colimits
      (i.e. compact)
- "hand wavy" definition of presentable
  - $C$ is presentable if there exists $C^0\subset C$ a full
    subcategory with objects in $C^0$ all "compact" and $C\cong
    Ind(C^0)$
    - $ob Ind(C^0)$ - $Fun(\mathbb{Z}, C^0)$  --- we actually need to
      vary $\mathbb{Z}$
    - morphisms $\lim\colim Hom(A_\alpha, B_\beta)$
  - Example - $P(D)$, $D$ a small $\infty$-category
    - Fact: Any presentable category is a localization of $P(D) for
      some $D$.
    - Suppose $D=*=\Delta_0$. Then $P(D)=S$.
  - Property we actually need: Given $Fun^{colim}(P(D), C)\subet
    Fun(P(D), C)$ consiting of limit preserving functors, and $D$
    presentable, $Fun^{colim}(D,C)\cong Fun(D^{gen},C)$
- We had $X\xrightarrow{f}Y$ a geometric morphisms.
  - Let $F\in Shv_Y(C)$, $F:Y^{op}\rightarrow C$, with $C$
    presentable. Then, by Adjoint functor theorem (see MacLane or
    Lurie), there exists a left adjoint $C\xrightarrow{G}Y^{op}$ which
    preserves colimits.
  - Then $C^{fin}\rightarrow Y^{op}\xrightarrow
    {F^!}X^{op}$. Composing $f^{!}\tilde G:C^{fin}\rightarrow
    X^{op}$. This extends to a colimit preserving functor
    $C\rightarrow X^{op}$, so by adjoint functor theorem there exists
    $X^{op}\rightarrow C$ which preserves limits.
  - This assembles to a functor
    $Shv_Y(C)\xrightarrow{f^*}Shv_X(C)$. Further, by construction we
    have an adjoint pair.
- Alternative definition of $Shv_T$ where $T$ is a Small category with
  a grothendieck topology.
  - Recall a sieve over $x\in T$ is a subcategory of $T/x$.
  - A functor $F:T^{op}\rightarrow C$ is a sheaf if for any "covering"
    sieve of $x$, $U\subset T/X$,
    $$ U^{op}\subset (T/x)^{op}\xrightarrow{i}T^{op}\xrightarrow{F}C$
    $lim F_i\cong F(X)$
  - Fact, in $T/X\rightarrow{i}T$, $\colim i\cong X$
  - *Exercises* When $C=S$, show this matches our previous definition
  - Advantage: No Yoneda!
  - *Proposition* $Shv_T(C)\cong Shv_{Shv_T}(C)$
    - $Shv_{Shv_T}(C)\cong Fun^{lim}(Shv_T^{op}, C)\rightarrow
      Fun(T^{op}, C)$
    - $i:Shv_T\leftrightarrows P(T):L$ gives
      $$Fun(Shv_T^{op},C)\leftrightarrows Fun^{colim}(P(T)^{op},
      C)\cong Fun(T^{op}, C)$$
    - $Since, for any sieve $U\subset h_X$, $L(U)\cong L(h_X)$, thus
      $Shv_{Shv_T}(C)\subset Shv_T(C)$.
    - In actuality, the condition on covering sieves *is* the sheaf
      condition, so this is an equivalence.
- Let $C$ be an $\infty$-cat with finite colimits (think $C=N(k-alg^{fin})$)
- An admissible topology on $C$ consists of
  - A class of morphisms in $C$ called "admissible morphisms"
  - For each object $A\in C$, a class of functors $\{A\rightarrow
    A_\alpha}$ of admissible morphisms called covering families satisfying
    - Any morphisms equivalent to an admissible morphism is admissible.
    - $id$ is admissible
    - composition of admissible morphisms is admissible.
    - transitivity: If $\{A\rightarrow A_\alpha\}$ and
      $\{A_\alpha\rightarrow A_{\alpha\beta}\}$ are covering, then
      $\{A\rightarrow A_{\alpha\beta}\}$ is covering
    - If $A\rightarrow A'$ is covering, and $A\rightarrow B$ is any
      morphism, then $B\rightarrow B\coprod_AA'$ is admissible.
    - If a family $\{A\rightarrow A_\alpha\}$ is a covering, then any
      larger family containing it is a covering family.
    - Any covering family contains a finite covering subfamily.
  - Examples
    - trivial: admissible iff equivalence, covering iff contains an admissible
    - Zar
      - $A\rightarrow A_a$ is admissible, for $a\in A$
      - $\{A\rightarrow A_\alpha\}_C$ is a covering, if there exists a
        (finite) subset $B\subset C$ s.t. $(a_\beta)_{\beta\in B$\cong
        A$.
    - Étale
