#+TITLE: Notes for Higher Category Theory
#+LATEX_HEADER: \usepackage{amsthm}
#+LATEX_HEADER: \usepackage{empheq}
#+LATEX_HEADER: \newtheorem{definition}{Definition}
#+LATEX_HEADER: \newtheorem{examples}{Example}
#+MATHJAX: mathml:t
#+LINK_HOME: index
#+BABEL :exports results

* Notes for 2011-09-16
:PROPERTIES:
:ID:       f443edc2-532b-4a1f-a90e-9fae0d1cc0fb
:END:
** Books
1. T.Y. Lam - Lectures on Modules and Rings
2. Charles Weibel - A Introduction to Homological Algebra
3. Dames R. Munkres - Elements Of Algebraic Topology
4. James Davis and Paul Kirk - [[http://www.maths.ed.ac.uk/~aar/papers/davkir.pdf][Lecture Notes in Algebraic Topology]]
5. Structured Ring Spectra

** Reading for [2011-09-16]--[2011-09-26]
1. Homotopy Theory and Model Categories by Dwyer and Spalinski
   [[http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.152.8004][CiteSeer]]
2. An elementary illustrated introduction to Simplicial Sets by G. Friedman
   [[http://arxiv.org/abs/0809.4221][arXiv]]
3. Fiber Bundles - [[http://www.math.cornell.edu/~hatcher/AT/AT.pdf#page=385][pp.375-384 in Hatcher]]
** Fibrations and Cofibrations in $Top$
- $Top$ is the category of compactly generated topological spaces

*** Definition 							 :DEFINITION:
A continuous map $p: E\rightarrow B$ is a *fibration* if we have a
solution to the following lifting problem:
#+begin_src latex :file diag1.svg
\begin{diagram}
  Y\times \{0\} & \rTo & E \\
  \dTo & \ruDotsto & \dTo \\
  Y\times I & \rTo & B
\end{diagram}
#+end_src

*** Examples
**** Covering Spaces (for which there exists a unique lift)	    :EXAMPLE:
**** Fiber bundles (over a paracompact base)			    :EXAMPLE:
**** Pullback fibrations					    :EXAMPLE:
If $p:E\rightarrow B$ is a fibration and $f: X\rightarrow B$ is a
continuous map, consider the space $f^*(E) = \{(x,e)\in X\times E |
f(x)=p(x)\}$
Then we have the diagram
#+begin_src latex :file diag2.svg
\begin{diagram}
  f^*(E)\SEpbk & \rTo^{\pi_1} & E \\
  \dTo^{\pi_2} & & \dTo_p \\
  X & \rTo_f & B
\end{diagram}
#+end_src

1. What is $\pi_2$?

   The restriction of $X\times E \rightarrow X$ to $f*(E)\subseteq
   X\times E$.

2. Pullbacks have a good universal property

   We have the diagram
#+begin_src latex :file diag3.svg
  \begin{diagram}
    Q \\
    &\rdTo(2,4)_{q_2}\rdDotsto^{\exists!u}\rdTo(4,2)^{q_1}\\
    &&f^*(E)\SEpbk & \rTo^{\pi_1} & E \\
    &&\dTo^{\pi_2} & & \dTo_p \\
    &&X & \rTo_f & B
  \end{diagram}
#+end_src

   where $\pi_2\circ u = q_2$ and $pi_1\circ u = q_1$.

3. We can form the diagram
#+begin_src latex :file diag4.svg
  \begin{diagram}
    Y\times\{0\}&\rTo&f^*(E)\SEpbk & \rTo^{\pi_1} & E \\
    \dTo&\ruDotsto(3,1)^{\exists H}&\dTo^{\pi_2} & & \dTo_p \\
    Y\times I&\rTo&X & \rTo_f & B
  \end{diagram}
#+end_src
   Since $p$ is a fibration, there exists a map $H$ making the
   diagram commute. Then we have,
#+begin_src latex :file diag5.svg
  \begin{diagram}
    Y\times\{0\}&\rTo&f^*(E)\SEpbk & \rTo^{\pi_1} & E \\
    \dTo&\ruTo^{\exists H'}\ruDotsto(3,1)^{\exists H}&\dTo^{\pi_2} & & \dTo_p \\
    Y\times I&\rTo&X & \rTo_f & B
  \end{diagram}
#+end_src
   by the universal property, where $Q=Y\times I$, $q_1=H$, and then
   $H'=u$.

   Exercise: Show that H' is a lift.
**** Path Space Fibrations					    :EXAMPLE:

Given a continuous map $f:X\rightarrow Y$ where $Y$ is path
connected.

Can replace $X$ by a homotopy equivalent space $P_f$.

- Build $P_f$ (start with Y)

  $Y^I\coloneqq Map(I,Y)$ with the (approximately) the compact
  open topology.

  * Step 1. $q:Y^I\rightarrow Y$ is a
    fibration. ($q:\alpha\mapsto\alpha(a)$)
  * Step 2.
#+BEGIN_SRC latex :file diag6.svg
  \begin{diagram}
    P_f:=&f^*(Y^I)\SEpbk&\rTo^{\pi_1}&Y^I \\
    &\dTo^{\pi_2}&&\dTo_q\\
    &X&\rTo_f&Y
  \end{diagram}
#+END_SRC

    The pullback $P_f\xrightarrow{\pi_2}X$ is a fibration.

*** Last thing to say about fibrations

There are examples that don't come from fiber bundles

**** Project 1 (20 minute talk) 				    :PROJECT:
Give an example of these fibrations (with applications).
- Hopf/Serre Fibration

** Cofbirations
Let $A$, $X$ be reasonable spaces (e.g. CW-complexes).

*** Definition							 :DEFINITION:
$i: A\rightarrow X$ is a *cofibration* if there exists a lift $H$
#+BEGIN_SRC latex :file diag7.svg
  \begin{diagram}
    X\times\{0\} \cup A\times I & \rTo^{f\cup  h} & y \\
    \dTo & \ruDotsto_{\exists H}\\
    X\times I
  \end{diagram}
#+END_SRC

for any map $f:X\rightarrow Y$ and $h:A\times I \rightarrow Y$ a
homotopy extending $f|_A$.

A cofibration is essentially an embedding whose image is
closed. The intuition is that the homotopy on the boundary of $A$
can be extended.

*** Key points about cofibrations
Cofibrations are *dual* to fibrations.

$A\times I\xrightarrow{f}B$ is dual to $A\rightarrow B^I$.

$f:X\rightarrow Y$ is a fibration if
#+begin_src latex :file diag8.svg
\begin{diagram}
  X&\lTo^{ev_0}&X^I \\
  \uTo&\ruDotsto&\dTo^f\\
  Z&\rTo&Y^I
\end{diagram}
#+end_src

$f:Y\rightarrow X$ is a cofibration if
#+begin_src latex :file diag9.svg
\begin{diagram}
  X&\rTo^{i_0}&X\times I \\
  \dTo&\ldDotsto&\uTo^{f\times I}\\
  Z&\lTo&Y\times I
\end{diagram}
#+end_src

*** Key points about cofibrations 2
**** Definition (Pushout) 					 :DEFINITION:
Let $f:A\rightarrow B$ and $g:A\rightarrow C$ be continuous maps.

We have
#+BEGIN_SRC latex :file diag10.svg
  \begin{diagram}
    A&\rTo^f&B\\
    \dTo_g&&\dTo&\rdTo(2,4)\\
    C&\rTo&\NWpbk f_*C \\
    &\rdTo(4,2)&&\rdDotsto^{\exists!} \\
    &&&&D
\end{diagram}
#+END_SRC

where $f_*C \coloneqq B\sqcup C/f(a)\sim g(a)$ and $B\sqcup
C\coloneqq\{(b,c_0,0)\in B\times C\times I |b\in B\} \cup
C\coloneqq\{(b_0,c,1)\in B\times C\times I |c\in C\}$

In $Top$, we can always construct $f_*C$.

**** Theorem							    :THEOREM:
If $g:A\rightarrow C$ is a cofibration, then
#+BEGIN_SRC latex :file diag11.svg
  \begin{diagram}
    A&\rTo^f&B\\
    \dTo_g&&\dTo\\
    C&\rTo&\NWpbk f_*C \\
\end{diagram}
#+END_SRC
$B\rightarrow f_*C$ is also a cofbiration

Proof. dual to that for cofibrations.

**** Mapping Cylinders 						    :EXAMPLE:
Let $f:A\rightarrow X$ be continuous.
We replace $X$ by a homotopy equilvaent space

Define $M_f$ such that $A\rightarrow M_f$ is a cofibration.

#+BEGIN_SRC latex :file diag12.svg
  \begin{diagram}
    A\times\{1\}&\rTo&X\times\{1\}\\
    \dTo&&\dTo \\
    A\times I&\rTo&M_f
  \end{diagram}
#+END_SRC

$M_f$ is the mapping cylinder of $f$.

*** Model Categories
We axiomatics these properties of $Top$.

Then we can use all the power of homotopy theory in general
settings.

Let $\mathscr{C}$ be a nice category and $W$ weak equivalences (a
distinguished class of maps in $\mathscr{C}$. Then the object of
study is $\mathscr{C}[W^{-1}]$. In the topological setting this is
$Top/homptopy$, and the category on which $\pi_*X$ is defined.

We have a functor
\(\mathscr{C}\xrightarrow{\mathscr{L}\text{invert $W$}}
\mathscr{C}[W^{-1}]\eqqcolon Ho(\mathscr{C})\). $Ho(\mathscr{C}$
is called the homotopy category or derived category.

We are interested in $Map_{Ho(\mathscr{C})}(X,Y)$, $\pi_*(X)$,
$H_*(X)$ in $Ho(\mathscr{C})$. We have various models of what
happens in $Ho(\mathscr{C})$:
- Higher Category Theory
- $(\infty,1)$-categories
- Quasi-categories
- Complete Segal Spaces

The behaviour is governed by the cofibrations and fibrations.

** Basic Objects

*** Definition							 :DEFINITION:
A (small) *category* $\mathscr{C}$ consists of
1) A set of objects $obj(\mathscr{C})$
2) For every $X,Y\in obj(\mathscr{C})$ a set
   $Hom_{\mathscr{C}}(X,Y)$ of maps $X\rightarrow Y)
3) An associative and unital composition.

*** Definition							 :DEFINITION:
A category $\mathscr{C}$ is *enriched* over a category
$(\mathscr{D},\otimes,1)$ if it has
1) A set of objects $obj(\mathscr{C})$
2) $Hom_{\mathscr{C}}(X,Y)$ is an object of $\mathscr{D}$
3) $\mathscr{D} has a multiplication, so
   $Hom(X,Y)\otimes Hom(Y,Z)\rightarrow Hom(X,Y)$
   is given by the multiplication.

**** Example							    :EXAMPLE:
$Ho(\mathscr{C})$ can be transformed into a category enriched in
"spaces". (This is a $(\infty,1)$-category)


Given $\mathscr{C}$ + a model structure, we can form (via
$\mathscr{L}$ the homotopy category $Ho(\mathscr C)$. From that, we
can for the Dwyer-Kan localization $\mathscr{LH}$ of
$Ho(\mathscr{C}$ to get a simplicial category (aka
$(\infty,1)$-category).

**** Project							    :PROJECT:
A dg-category $\mathscr{C}$ is a category enriched in chain complexes

*** Functor 							 :DEFINITION:
A map of categories (*functor*) $F:C\rightarrow D$ is  given by
1) $F_0:obj(\mathscr{C})\rightarrow obj(\mathscr{D})$ set map
   between objects
2) $F_{x,y}:Hom_{\mathscr{C}}(X,Y) \rightarrow
   Hom_{\mathscr{D}}(F_0X, F_0Y)$
3) maps compatible with the composition

**** Properties of functors
1) $F:\mathscr{C}\rightarrow\mathscr{D}$ is an *equivalence* if there exists
   $G:\mathscr{D}\rightarrow\mathscr{C}$ such that $GF\simeq
   id_{\mathscr{C}}$ and $FG\simeq id_{mathscr{D}}$.

   Note: the idea is to think of a category as a space.

2) $F:\mathscr{C}\rightarrow\mathscr{D}$ is *full* if $F_{X,Y}$ is
   surjective for every $X,Y\in\mathscr{C}$ and *faithful* if it
   is injective.
3) $F:\mathscr{C}\rightarrow\mathscr{D}$ is *essentially
   surjective* if forall $d\in\mathscr{D}$, there exists
   $c\in\mathscr{C}$ such that $d\simeq F_0(c)$.

*** Nerves
$\mathscr{C}\xmapsto{\text{nerve}}N(\mathscr{C})$ is a
space. $F:\mathscr{C}\rightarrow\mathscr{D}$ is a weak equivalence
if $NF$ is a weak equivalence.

Fibrations in $Cat$. A functor is a fibration if every nice path
(isomorphism) lifts.

* Notes for 2011-09-20
:PROPERTIES:
:ID: d7138a37-7cbf-4862-aadd-18f0ba7596ef
:END:

- Examples of Model Categories
  - In particular, the fibrant and cofibrant objects in them.

** Why Model Categories.
Given $\mathscr C$ a category, and subcategory $\mathscr W\subseteq
\mathscr C$ of weak equivalences.

If $\mathscr C$ is a model category
- $Ho\mathscr{C} = \mathscr{C}[W^{-1}] where
- $obj(Ho\mathscr C) = \obj\mathscr C$
- $Hom_{Ho\mathscr C}(X,Y)=[X_c,Y_f]$
  homotopy classes of maps where
  - $X_c$ is a cofibrant replacement of $X$
  - $Y_f$ is a fibrant replacement of $Y$.
*** What is a cofibrantly generated model category.
- transfinite composition
  (think countable except for things like presheaves)
  - Hovey just uses induction
**** Cofibrantly Generated model categories 			 :DEFINITION:
A model category $\mathscr C$ is cofibrantly generated if there
exists a _set_ of cofibrations $I$ (resp. trivial cofibrations
$J$) such that all other cofibrations (resp.) are "generated" by
$I$ (resp. $J$).

- staturation ("generated") is closure under pushout and countable
  (transfinite) composition
**** Maps in a category                                          :DEFINITION:
Let $\mathscr C$ a category, $I$ a *class* of maps in $\mathscr C$. A
map is
1) $I$-injective ($I-inj$) iff it has the RLP wrt all maps in $I$.
2) $I$-projective ($I-proj$) iff it has the RLP wrt all maps in $I$.
3) an $I$-cofibration ($I-cof$) iff it has the LLP wrt $I-inj$.
   $I-cof=(I-inj)-proj$
4) an $I$-fibration ($I-fib$) iff it has the RLP wrt $I-proj$.
   $I-fib=(I-proj)-inj$
***** Examples                                                      :EXAMPLE:
If $\mathscr C$ is a model category, with $W$, $F$, $C$ then
- $C-inj$ = F\cap W$ - trivial fibrations
- $C-cof = C$ - cofibrations
- $F-proj = C\cap W$ - trivial cofibrations
- $F-fib = F$ - fibrations

***** Relations
1) $I\subseteq I-cof$
   $I\subseteq I-fib$
2) $(I-cof)-inj = I-inj$
3) $(I-fib)-proj = I-proj$
4) $I\subseteq J$ implies
   - $J-inj \subseteq I-inj$
   - $J-proj \subseteq I-proj$

***** Remark
Usually $I-cof$ has little to do with $I$.
- If we want to stufy cofibrations (fibrations) we need to pick our
  generators carefully.

***** Relative cell complexes                                    :DEFINITION:
Let $I$ be a *set* of maps in $\mathscr C$ (where $\mathscr C$ has all
small colimits).

A *relative $I$-cell-complex* ($I-cell$) is a countable (transfinite) composition
of pushouts of maps in $I$.

If $f:A\rightarrow B$ is a relative $I$-cell complex, then there
exists an ordinal $\lambda$ and a $\lambda$-sequence
$X:\lambda\rightarrow\mathscr C$ such that the $f$ is the composition
of $X$.

- $X:\lambda\rightarrow\mathscr C$.

  $\underbrace{X_0\rightarrowX_1\rightarrow\cdots\rightarrow
  X_n\xrightarrow{h_n}\cdots}_X$

#+BEGIN_SRC latex :file diag14.svg
  \begin{diagram}
     C_\beta&\rTo&X_\beta\\
     \dTo^{q_\beta\in I}&&\dTo^{h_\beta}\\
     D_\beta&\rTo&\NWpbk X_{\beta+1}\\
   \end{digram}
#+END_SRC

$A\in\mathscr C$ is a *cell complex* (relative cell
complex in Hovey) if $0\rightarrow
A$ is (where $0$ is the initial object in $\mathscr C$).

****** CW-complexes                                             :EXAMPLE:
A relative $CW-$ complex is a relative cell complex where all cells
are attach in order of dimension.

****** id                                                           :EXAMPLE:
$id:A\rightarrow A$ is always a relative $I$-cell complex

****** Lemma                                                          :LEMMA:
$I$-cell \subseteq I-cof$


*** Model Structures directly from Axioms                           :EXAMPLE:
- Categories
- $Ch(R)_{\ge0}$
- Sets

*** Trick 1                                                    :DEFINITION:
Suppose $\mathscr C$ is a model category.

We say $\mathscr C$ is cofibrantly generated if there exists sets $I$,
$J$ such that
1) the domains of maps of $I$ (resp. $J$) are small relative to
   $I-cell$ (resp. $J$-cell).
2) fibrations are $J-inj$.
3) trivial fibrations are $I-inj$
with $I$ (resp. $J$) the set of generating cofibrations (resp. trivial cofibrations).

**** Remarks
1) If all domains of $I$ and $J$ are *compact* objects of $\mathscr C$
   then $\mathscr C$ is a *cellular* model category.
   - In which case $I-cof=I-cell$.
   - Exmaples: $Ch_{\ge0}(R)$, $Ch(R)$, stable $R$-modules
   - Non-example: $Top$
2) A cofibrantly generated model category $\mathscr C$ which is also
   locally presentable is a *combinatorial* model category
   ($(\infty,1)-category).

**** Smallness
[[file:smallness.org][Alternative presentation]]

$f:A\rightarrow B$ in $I$.
$X:\rightarrow Y$ a relative $I$-cell complex then
$colim \mathscr C(A,X_\beta)=\mathscr C(A,colim X_\beta)$.

**** Why cofibrantly generated?
A. It is actually easier to find a cofibrantly generated model structure on
$\mathscr C$ than just putting a model structure on $\mathscr C$.

**** Theorem (Kan)                                                  :THEOREM:
Suppose $\mathscr C$ is a category with all small limits and colimits,
$W$ a subcategory of weak equivalences, $I$, $J$ sets of maps in
$\mathscr C$.

Then, under the following conditions, there exists a cofibrantly
generated model structure such that $W$ is the set of weak
equivalences and $I$ and $J$ are the generating cofibrations
(resp. trivial cofibrations).
1) W has the 2-out-of-3 property and is closed under retratcs.
2) domains of maps in $I$ and $J$ are small relative to $I-cell$ (resp $J-cell$)
3) $J-cell\subseteq W\cap J-cof$  -- classifying fibrations
4) $I-inj\substeq W\cap J-inj$ -- classifying trivial fibrations
5) (hard) Either
   - $W\cap I-cof \subseteq J-cof$
   - $W\cap J-inj \subseteq I-inj$
   If a map is a cofibration and a weak equivalence then it is a
   trivial cofibration

**** Quillen Adjuntion                                           :DEFINITION:
Cofibrantly generated model structures make transferring homotopy
easier.

$F:\mathscr{C}{\rightarrow\atop\leftarrow}\mathscr D:U$.
where $\mathscr C$, $\mathscr D$ are model categories, $F$ and $U$
adjoint (the left adjoint is written on top)

$(F,U)$ is a *quillen adjunciton* if
- $F$ preserves cofibrant objects and equivalences between them
or
- $U$ preserves fibrant objects and equivalences between them

If $\mathscr C$ is cofibrantly generated then $(F,U)$ is a Quillen
adjunction if $Ff$ is a cofibration (resp. trivially cofibration) in
$D when $f\in I$ (resp. $f\in J$.

***** Problem
$Cat {\xrightarrow{N}\atop\xleftarrow[\tau]{}} sSet_*$ where
$sSet_*$ has the Joyal model structure.

**** $Top$
- Fact(Exercise) Not every object in $Top$ is small.
***** Sierpinski Space $S$                                          :EXAMPLE:
Open sets: $\{\}$, $\{x\}$, $\{x,y\}$

Let $\lambda$ be a limit ordinal, $Y=\lambda+1$ with the order
topology.

$X_\alpha=Y\times\{0,1\}/(x,0)\sim(x,1)\text{ if }x<\alpha$.

$X=colim_{\alpha<\lambda} X_\alpha = Y\cup (\lambda,1)$.

There exists a map from $S$ to $X$ that does not factor through the
limit.
***** Facts
where $Top$ is compactly generated spaces (originally shown by
Quillen)

- $f:X\rightarrow Y$ is a weak equivalence if
  $\pi_n(f,x):\pi_n(X,x)\rightarrow\pi_n(Y,f(x))$ is an isomorphism
  for all $n\ge0$ and $x\in X$.

- \(I'=\{\text{boundary inclusions }S^{n-1}\hookrightarrow D^n\}\)

- \(J=\{\text{inclusions }D^n\rightarrow D\times I^n\}\)

$f$ is a cofibration if $f\in I'-cof$
$f$ is a fibration if $f\in J-inj$.

Exercise: show that fibrations are the Serre fibrations

maps of $J$ are relative CW-complexes

fibrant objects are all spaces
cofibrant objects are retracts of CW-complexes

* Notes for 2011-09-23
:PROPERTIES:
:ID: 542fb78e-5cde-4a19-9eef-b781940dfc3a
:END:

** Review
$\mathscr C$ a model category, then there is a $Ho(\mathscr C) =
\mathscr C[W^{-1}]$, where
- Objects are $obj\mathscr C$
- maps $Hom_{Ho(\mathscr C)}(X,Y)\coloneq[X_c,Y_f]$

$Ho\mathscr C\xrightarrow{\mathscr {LH}}\text{simplicial
category}$.

** Example (Digression on $D(R)$
$D(R)=Ho(Ch_(\ge0))
- objects are $M^\bullet$
- $D(R)(M^\bullet,N^\bullet) = [QM^\buulet, N^\bullet]$
  - where $Q$ is projective resolution, every object is fibrant.
- $Hom(M^{\triangle},N^\bullet)\eqqcolon Map^h(M^\bullet,N^\bullet)$
** Example ($Top$) (Quillen 1967)
- compactly generated topological spaces, pointed

Let $f: X\rightarrow Y$ a continuous map
- $f$ is an *inclusion* if $U$ is open in $X$ iff there exists an
  open $V$ in Y$ such that $f^{-1}(V)=U$.

  - Lemma
    Every topological space is small wrt inclusions.
    - Proof
     Let $\lambda$ be an ordinal, $X:\lambda\rightarrow Top$ is a
     $\lambda$-sequence of inclusions

     $X_0\xrightarrow{h_0}X_1\xrightarrow{h_1}->\cdots\rightarrow
     X_\alpha\xrightarrow{h_\alpha}X_{\alpha+1}\cdots$

      - By composition, each $X_\alpha\rightarrow X\beta$ is also an
	inclusion for any $\beta>\alpha$.
      - implies $X_\alpha \rightarrow colim_{x<\lambda}X_x$
	(consider $colim_n(X_0\subset X_1\subset\cdots\subset X_n)
      - For any $f:A \xrightarrow colim_{\alpha<\lambda} X_\alpha$, we
	want a factorization through some $X_\alpha$.

	It will suffice to that $f(A)\subseteq X_\alpha$ for some
	$\alpha<\lambda$.

	Sets are small:
	$colim_{\alpha<\lambda}Hom(A,X_\alpha)=Hom(A,colim_{\alpha<\lambda}X_\alpha$
	for every $A$ and some $\lambda$ (condition is $\lambda>|A|$.
  - If you have "sets" underlying objects then there is no need for
    smallness arguments.
  - Remark: For inclusions, we can lift continuity from Sets to
    $Top$.
  - Almost always, we define cofibration so that they have this
    property. i.e. cofibrations "=" inclusions

*** Model structure on $Top$
Given $X\in Top$, $x\in X$ a basepoint

$\pi_n(X,x) = Map((S^n,*),(X,x))$
$f:X\rightarrow Y$ is a weak homotopy equivalence if
$\pi_f:\pi_*(X,x)\rightarrow\pi_(Y,fx)$ is a bijection for $*\ge
0$ and $x\in X$.

$I\coloneqq\{\text{boundary inclusions }S^{n-1}\hookrightarrow D^n | n\ge 0\}$
where $S^{-1}=\emptyset$ and $D^n=\{0\}$.

$J\coloneqq\{D^n\rightarrow D^n\times I|N\ge 0\}$ where the maps
are given by $x\mapsto (x,0)$.

Theorem(Quillen '67) Top has a cofibrantly generated model
structure with w.e. given by the weak homotopy equivalences.
- $I$ = generating cofibrations
- $J$ = generating acyclic cofibrations

Remember $f:A\rightarrow B$ a cofibrations does not imply $f\in
I$. $f\in\overline I=\text{staturation of }I$.
$A=\overbrace{X_0\xrightarrow{h_0}X_1\rightarrow\cdots\rightarrow
 X_\beta\rightarrow B}^h$
Where
#+BEGIN_SRC latex :file diag13.svg
  \begin{diagram}
    C&\rTo&X_\alpha\\
    \dTo^{i\in I}&&\dTo_{h_\alpha}\\
    D&\rTo&\NWpbki X_{\alpha+1}
  \end{diagram}
#+END_SRC

- Fibrations = Serre fibrations are /defined/ by having the RLP
  wrt maps in $\overline J$
#+BEGIN_SRC latex :file diag13.svg
  \begin{diagram}
    A&\rTo&X\\
    \dTo^j&\ruDotsto{\exists H}&\dTo_p\\
    B&\rTo&Y
  \end{diagram}
#+END_SRC
  $p$ is a fibration iff $\exists H$, $j\in\overline J$ such that
  the above diagram commutes.

- Proof of Thm (Kan's Theorem)

  1) We are closed under retracts (retracts of spaces are homotopy
        invariant) and have the 2-out-of-3 property
  2) Classify fibrations
	   $p:X\rightarrow Y$ is a fib iff $p$ has the RLP wrt $\overline J$.
  3) Classify trivial fibrations
	   $p:X\rightarrow Y$ is a fib iff $p$ has theRLP wrt $\overline I$
  4) (Hard) If $f\in \overline J$ then $f$ is a weak homotopy
     equivalence.

     - Lemma
	     Every map in $J-cof$ is a trivial cofibration.

	     Pf (Sketch)
       1) Every map in $J-cof$ is a cofibration
          - $I-cof$ is the cofibrations.
          - $J\subset \overline I$
       2) Every map in $J-cof$ is a weak homotopy equivalence

	       $A\xrightarrow{i} B$ is a deformation retract if
         $\exists$ a homotopy $H:B\times I\rightarrow B$
         s.t. $H(i(a),t)=i(a)$, $H(b,0)=b$, $H(b,1)=ir(b)$, where
         $r:B\rightarrow A$.

	       - Fact :: The inclusion of a deformation retract is a weak
          homotopy equivalence. (check on $\pi_1$).

	       - Fact :: Every map of $J$ is the inclusion of a
          deformation retract.

	       - Fact :: Inclusions of deformation retracts are closed
          under pushouts.

	     #+BEGIN_SRC latex :file diag14.svg
         \begin{diagram}
            A&\rTo&C\\
            \dTo^{i\in J}&&\dTo^j\\
            B&\rTo&\NWpbk D
          \end{diagram}
	     #+END_SRC

	     $D\times I=(B\times I)\times_{A\times I}(C\times I)$
       (locally Hausdorff spaces are cartesian closed)

	     $K:B\times I\rightarrow B$ is the homotopy that makes
       $i$ a inclusion of a deformation retract.

	     $gK+C\times I\rightarrow D$, $(c,t)\mapsto jc$ gives
       $H:D\times I\rightarrow D$, which gives the deformation
       retract of $j$.

       - Took $i$ and inclusion deformation retract.
         - Used $i$ is a weak homotopy equivalence
       - Took the pushout of $i$, to get $j$. Then $j$ is the
         inclusion of a deformation retract by $H$.
       - Implies that $j$ is a weak equivalence.
       - Every map in $J$ is a inclusion of deformation
         retract.
         - transfinite pushouts of maps in $J$ are inclusion
           deformation retracts
         - transfinite pushouts of maps in $J are w.e.
         - because w.e. satisfy 2-out-of-3, every map in
           $J-cof$ is a weak homotopy equivalence.

*Point*
The small object arguments is "in" this proof.
$X\xrightarrow{f}Y$
$X\xrightarrow{~}M\rightarrow Y$ (build $M$ out of cells)

How do you use this proof to
- Show that the cofibrant objects in $Top$ are retracts of cell
  complexes?
  - $A$ is a cofibrant if $*\hookrightarrow A$ is a cofibration?
#+BEGIN_SRC latex :file diag15.svg
\begin{diagram}
  S^{n-1}&\rTo&*\\
  \dTo&&\dTo\\
  D^n\rTo&&\NWpbk A_0\\
\end{diagram}
#+END_SRC
* Notes for 2011-09-27
:PROPERTIES:
:ID:       31180905-5bdf-434d-b5d1-16d8e63c2453
:END:
** Reading for [2011-09-28]-[2011-10-10]
- Ch 1 - [[http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.144.9438][Basics in Enriched Category Theory]] by GM Kelly
** 1
$\mathscr M$ is a model category then $Ho\mathscr M$ is a category

Q: What is the homotopy category? What is the derived category?

A1: $Ho\mathscr M$ is the *component category* of a simplicial
category.
A2: If $M$ is the "stable homotopy category" then
$Ho\mathscr{M}=\mathbb{S}-mod$.

** Monoidal category                                             :DEFINITION:
A *monoidal category* $\mathscr{V}=(V_0,\otimes,I,a,\ell,r)$ consists of
1) a category $V_0$
2) A functor $\otimes:V_0\times V_0\rightarrow V_0$
3) an object $I\in V_0$
natural isomorphism.
1) $a_{xyz}:(x\otimes y)\otimes z\rightarrow X\otimes(Y\otimes Z)$
2) $\ell_x:I\otimes X\rightarrow X$
3) $r_x:X\otimes I\rightarrow X$
subject to the following coherence diagrams
1)
#+BEGIN_SRC latex :file diag16.svg
  \begin{diagram}
    ((W\otimes X)\otimes Y)\otimes Z&\rTo^{a}&(W\otimes X)\otimes(Y\otimes Z)\\
    &&\dTo_a\\
    \dTo^{a\otimes 1}&&W\otimes(X\otimes(Y\otimes Z))\\
    &&\uTo_{1\otimes a}\\
    (W\otimes(X\otimes Y))\otimes Z&\rTo&W\otimes((X\otimes Y)\otimes Z)
  \end{diagram}
#+END_SRC

2)
#+BEGIN_SRC latex :file diag17.svg
  \begin{diagram}
    (X\otimes I)\otimes Y & &\rTo&&X\otimes(I\otimes Y)\\
    &\rdTo^{r\otimes 1}&&\ldTo_{1\otimes \ell}\\
    && X\otimes Y
  \end{diagram}
#+END_SRC

A special case: $\mathscr{V}$ is called a *cartesian monoidal* category if $V_0$
is a category with all finite products, $\otimes=\times$, $I=1$ is
terminal object, $a$, $\ell$, $r$ are the cannonicl isomorphisms

*** Examples                                                      :EXAMPLE:
Cartesian monoidal categories:
- $Set$
- $Cat$
- $Top$
- $Shv(S)$
Non-Cartesian:
- $Ab$, $R-mod$, gradded $R-mod$, $dg-R-mod$

*** Closed monoidal                                            :DEFINITION:
A monoidal category $\mathscr V$ is said to be *closed* (cartesian closed if
$V_0$ is catesian) if $-\otimes Y: V_0\rightarrow V_0$ has a right adjoint
$\underline{Hom}(Y,_):V_0\leftarrow V_0$
so that we have the adjunction
$V(X\otimes Y,Z)=V(X, Hom(Y,Z))$
with unit $D:X\rightarrow Hom(Y,X\times Y)$
and counit (evaluation) $e:Hom(Y,Z)\otimes Y\rightarrow Z$.

*** Enriched category                                          :DEFINITION:
If we have $\mathscr V$ a closed monoidal category, we can "enrich".

A $\mathscr{V}-cat$ (a category *enriched* in $V$ $\mathscr A$ consists of
1) a set of objects $obj(\mathscr{A})$
2) a hom-object $\mathscr{A}(x,y)\in V_0$ for each $x,y\in obj(\mathscr{A})$
3) A composition $\mu=\mu_{xyz}:A(y,z)\otimes \mathscr A(x,y)\rightarrow
   A(y,z)$ for all $x$,$y$,$z$.
4) An identity $j_a:I\rightarrow A(x,x)$ for every $x\in \mathscr A$

satisfying
#+BEGIN_SRC latex :file diag18.svg
  \begin{diagram}
    (A(z,w)\otimes A(y,z))\otimes A(x,y)&&\rTo^a&&A(z,w)\otimes(A(y,z)\otimes A(x,y))\\
    \dTo^{\mu\otimes 1}&&&&\dTo_{1\otimes\mu}\\
    A(y,w)\otimes A(x,y)&&&&A(z,w)\otimes A(x,z)\\
    &\rdTo_\mu&&\ldTo_\mu\\
    &&A(x,w)
  \end{diagram}
#+END_SRC
and
#+BEGIN_SRC latex :file diag19.svg
  \begin{diagram}
    I\otimes A(x,x)&\rTo^\ell&A(x,x)&\lTo^r&A(x,x)\otimes I \\
    \dTo^{j\otimes 1}&\ruTo^\mu&&\luTo^\mu&\dTo^{1\otimes j} \\
    A(x,x)\otimes A(x,x)&& &&A(x,x)\otimes A(x,x)
  \end{diagram}
#+END_SRC

Note: *closed* monoidal structure necessary

**** Examples
- $\mathscr V = Set$
  $V-cat= Cat$
- $\mathscr V = Cat$
  $V-cat = 2-Cat$ (homotopy theorists: bicategory, since "nerve" is a
  bisimplical set.)
- $\mathscr V = Ab$
  $V-cat$ is addative categories
- $V=sSet$ or $Top$
  $V-cat$ is simplicial categories / topological categories
  $Cat_\Delta$

  For 2 $\mathscr{V}-cat$ $A, B$, a $\mathscr V$-functor (enriched
  functor) $T:A\rightarrow B$ consists of
  1) a set map $T:obj A\rightarrow obj B$
  2) $T_{xy}:A(x,y)\rightarrow B(Tx,Ty)$ a map of $\mathscr V$-objects
  subject to
  #+BEGIN_SRC latex :file diag20.svg
    \begin{diagram}
      A(y,z)\otimes A(x,y)&\rTo^{\mu_A}&A(x,z)\\
      \dTo^{T\otimes T}&&\dTo_T \\
      B(Ty,Tz)\otimes B(Tx,Ty)&\rTo_{\mu_B}& B(Tx,Ty)
    \end{diagram}
  #+END_SRC

 Theorem (Kelly et al.)
 - The 2-functor $(-)_0: \mathscr V-cat\rightarrow Cat$ is
   *representable*.

   Translation
   Denote by $\mathscr I$ the unit $\mathscr{V}-cat$ with 1-object $0$
   and $\mathscr{I}(0,0)=I$.

   A $V$-functor $X:\mathscr{I}\rightarrow\mathscr A$ is just picking
   out an object $X\in\mathscr A$.

   A $V$-natural transformation $f:X\rightarrow Y:\mathscr
   I\rightarrow \mathscr A$ consists of a single component
   $f:I\rightarrow A(X,Y)$.

 Def: The ordinary category *underlying* a $\mathscr{V}$-category $\mathscr
 A$ is $A_0=(\mathscr{A})_0=\mathscr{V}-Cat(\mathscr{I},\mathscr(A))$

 $A_0$ is the category with $obj A_0=obj\mathscr{A}$ and a map
 $f:X\rightarrow Y$ $in $\mathscr A_0$ is just an element
 $f:I\rightarrow A(X,Y)$.

 $A_0(X,Y)=\mathscr{V}(I,\mathscr{A}(X,Y))$

***** Example
$\mathscr{V}=Top$ or $sSets$ (write $Spaces$) (pointed)
- $Top=(CGHTop_*,\wedge,S^0)$

$\mathscr A$ a $\mathscr{V}-cat$, $A_0=\pi_0\mathscr{A}$ is the
component category of $\mathscr{A}$.
- $A_0$ has $obj\mathscr A$
- $A_0(x,y)=\pi_0\mathscr{A}(x,y)$

$Top(*,A(x,y))=Top((S^0,*),(A(x,y),*)) = \pi_0A(x,y)$

($\pi_0$ is the underlying set for now)

How much information is lost when one goes from a $\mathscr{V}-cat$
$\mathscr{A}$ to $A_0$?
- Answer depends on $\mathscr V$.

***** Awesome!
- $Ho(\mathscr{C})=\pi_0 L^H(\mathscr{C},W)$ - 1979 Dwyer-Kan


$\mathscr A$ is a simplicial category, $\mathscr A$ is also a model
category, "the homotopy theory of $\mathscr A$ interacts well with the
homotopy theory of spaces" (Quillen's SM7). Then $\mathscr A$ is a
simplicial model category.

$L^H(\mathscr A,W)$ is a simplicial category s.t $\pi_0L^H(\mathscr
A, W)=Ho(\mathscr{A})$ because $\mathscr A$ is a simplicial model
category.

$L^H(A,w)(X,Y)\coloneqq Map^h(X,y)=\mathscr{A}(X_c,Y_f)$.
$\mathscr{A}$ being simplicial means we have an easy way to /compute/
$Map^h(X,Y)$.

We are going to discuss 5 versions of $L^H(A,W)$.

***** Dwyer-Kan Hammock Localization
Let $\mathscr C$ be a small category, $W\subseteq \mathscr{C}$ be a wide
(contains all objects) subcategory. The *hammock localization* of $C$
wrt $W$ (^L^H(\mathscr {C},W)=L^H(\mathscr{C})$ is the simplicial category
1) $obj L^H\mathscr C$ has the same objects as $\mathscrC$
2) For $X,Y$ in $\mathscr C$, the simplicial set $L^H\mathscr{C}(X,Y)$
   has $k$-simplicies are the "reduced hammocks of width $k$, with any
   length" between $X$ and $Y$.

   #+BEGIN_SRC latex :file diag21.svg
     \newarrow{Dots}.....
     \begin{diagram}
       &&C_{0,1}&\rLine&C_{0,2}&\rLine&\cdots&\rLine&C_{0,n} \\
       &\ruLine&\dTo&&\dTo&&&&\dTo&\rdLine\\
       X&&C_{1,1}&\rLine&C_{1,2}&\rLine&\cdots&\rLine&C_{1,n}&&Y\\
       &\rdLine(2,3)&\dTo&&\dTo&&&&\dTo&\ruLine(2,3)\\
       &&\dDots&&\dDots&&&&\dDots\\
       &&C_{k,1}&\rLine&C_{k,2}&\rLine&\cdots&\rLine&C_{k,n} \\
     \end{diagram}
   #+END_SRC

   where
   - $n$ the length of the (rows) columns in any integer $\ge0$.
   - All vertical maps are in $W$
   - in each (row) column, all maps go in the same direction, if the
     go left then they are in $W$
   - Maps in adjacent (rows) colums go in different directions
   - No (row) column contains only $identity maps$

   $i$-face map = omitting the $i$th (column) row
   $i$-degeneracy map = repeating the $i$th (column) row

*Theorem* (D-k, 1979) For every $X,Y\in\mathscr C$ the components of
$L^H\mathscr{C}$ are in bijective corespondence with $X\rightarrow Y$
in $\mathscr C[W^{-1}]$

$\pi_0L^H(\mathscr{C},w)(X,y)\rightleftarrow\mathscr{C}[W^{-1}](X,Y)$

If $C$ is a *model category* then $L^H\mathscr{C}$ is *locally small*,
$L^H\mathscr{C}(X,Y)$ is a simplicial set.


****** Key facts about $L^H\mathscr{C}(X,Y)$
- The simplical category $L^H\mathscr{C,W}$ depends only on weak equivalences.
- If $M{rightarrow\atop\leftarrow}$ is a quillen equivalence, then the
  corresponding simplicial categories are "the same" (weakly
  equivalent).
- If $M$ is a model category, $L^HM(X,Y)$ is a *homotopy function
  complex* ($Map^h(X,Y)$).

  This space contains all higher homotopy information.

****** An explicit model of $Map^h$
1) Zig-Zag categories (Dwyer-Kan 1980)
   - For $X\in M$ and let $Q(X)$ be the category who's objects look like
     $(Q,Q\rightarrow X]$ where $Q$ is a cofibrant, $Q\righarrow X$ is a
     weak equivalence. The morphisms are the commutative
     triangles. (Slice of category of cofibrant objects over $X$)
   - For any object $Y\in M$,
     $M(-.Y): Q(X)^{op}\rightarrow Set$, $(Q,Q\rightarrow X)\mapsto
     M(Q,Y)$

     We can think of $M(-,Y)$ as being a functor to (discrete) spaces.

     We form a simplicial set $hocolim_{Q(X)^{op}}N(-,Y)$
     1) Simplicial resolution of diagram

        #+BEGIN_SRC latex :file diag22.svg
          \begin{diagram}
            Y&\lTo&Q_0&\lTo^{~}&Q_1&\lTo^{~}&\cdots&\lTo&Q_n\\
            &&&\rdTo(6,2)&&\rdTo(4,2)&&&\dTo\\
            &&&&&&&&X
          \end{diagram}
        #+END_SRC

     2) Take geometric realization

     3) 1+2 = $hocolim$

     Claim $hocolim M(-,Y)\rightarrow Map^h(X,Y)$
* Notes for 2011-09-30
:PROPERTIES:
:ID: e6d8a7f4-42a0-4550-8c76-81c768791618
:END:
** Review
- $H\xrightarrow{L^H}L^H(M)$ simplical category
- Spaces $L^H(M)(X,Y) = Map^{h}(X,Y)$
  - $\pi_0L^H(M)(X,Y)=[X,Y]$ homotopy classes
  - $\pi_1L^H(M)(X,Y)$ homotopies of maps between homotopies
** Monoidal model categories
- Model category with $\otimes$ so that $M$ is a closed monoidal
  category (in a homotopy coherent way).
  - then $M$ is a monoidal model category
- Monoidal model categories are to homotopy theory what rings are to
  an algebra
  - $M$ Spaces
    - is a monoidal model category
    - *modules* over spaces are simplicial model categories
    - a simplicial model category is an $S$-category, and the internal
      homs can be identified with $Map^h$ when $X$ is cofibrant and
      $Y$ is fibrant.
- Any monoidal model category has the the same properties as a
  simplicial properties
  - through the theory of homotopy function complexes
  - theory of framings/coframings (Hovey, Ch 5)
** Models of Hammock Localization
- $M$ a model category
- construct a $S$-category $L^H(M)$ with
  - $obj L^H(N)=obj M$
  - $L^(H)(M)(X,Y)$ have $k$-simplicies like
    {{diagram}}
    - pretty, but impossible to work with
- will build models that are easier to work with
  1) $Map^h(X,Y)$ is weakly equivalent to the nerve of $[X\xleftarrow{~}Q\rightarrow Y]$
  2) $Map^h(x,y)$ is equivalent to
     - $[n]\mapsto Hom(Q^n,Y_f)$ where
       - $Y_f\rightarrow Y$ is a fibrant replacement of $Y$
       - $Q^*X\rightarrow X$ is a cosimplicial resolution of $X$
  3) $[n]\mapsto Hom_M(X_c,R_nY)$ where
     - $X_c$ is a cofibrant replacement
     - $R_*Y\rightarrow Y$ is a simplicial resolution.
  4) $M$ is a simplicial model category - $Hom_M(X_c,Y_f)$
  5) $M$ is Morita model category, $M(X-Y-bimodule)$
*** Nerve of .
- The nerve of a category $C$ is the simplicial set $N(C)_*$ where
  - $N(C)_n$ is $n$-composable chains of morphisms
    - $C_0\rightarrow C_1\rightarrow\cdots\rightarrow C_n$
  - \(d_i(C_0\rightarrow\cdots\rightarrow C_n)=
    \begin{cases}
       C_0\rightarrow\cdots C_{i-1}\xrightarrow{a_{i+1}a_i}C_{i+1}\rightarrow\cots C_n \\
       C_0\rightarrow\cdots\rightarrow C_{n-1}&\text{where} i=n\\
       C_1\rightarrow\cdots\rightarrow C_n\text{where }i=0
    \end{cases}\)
  - $s_i$ is inserting and identity before the $i$th map.
**** Simplicial replacement
- $F:C\rightarrow Spaces$, we can replace $F$ by a a simplicial object.
- $(\coprod F)_n=\coprod_{C_0\cdots C_n\in N(C)_n} F(c_0)$
- Let $F(c_0)_\sigma$ to be the copy of $F(c_0)$ corresponding to
  the chain $\sigma\in N(C_0)_n$.
- we have an $(n+1)$-chain $s_1(\sigma)$ whose first element is
  again $c_0$, therefore we have another copy of $F(c_0)$
  corresponding to $s_1\sigma$ in $(\coprod F)_{n+1}.
  - $s_i:F(c_0)_\sigma\mapsto F(c_0)_{s_1\sigma}$
**** $[X\xleftarrow{~}Q\rightarrow Y$
- denotes the category where
  - an objects is a zig-zag of objects where $X\leftarrow U$ is a
    trivial fibration and $V\leftarrow Y$ is a trivial cofibration.
  - morphism
#+BEGIN_SRC latex :file diag23.svg
  \begin{diagram}
    &&U&\rightarrow&V \\
    &\ldTo&&&&\luTo \\
    X&&\dTo&&\dTo&&Y \\
    &\luTo&&&&\ldTo \\
    &&U&\rightarrow&V \\
  \end{diagram}
#+END_SRC
- $N([X\xleftarrow{~}U\rightarrow V\xleftarrow{~} Y])$
  - $k$-simplicies
    {{diagram}
    - is clearly a $k$-simplex of $L^H(M)(X,Y)$
    - Theorem (DK 1979)
      - $N([X\xleftarrow{~}U\rightarrow V\xleftarrow{~} Y])$ is
        w.e. to $Map^h(X,Y)$
- Problem: this is not much nicer
  - Claim
    - $Map^h(X,Y)\simeq N([X\xleftarrow{~}Q\rightarrow Y])$ where
      $Q$ is cofibrant and $Y$ is fibrant.
  - Why is $[X\xleftarrow{~}Q\rightarrow Y]$ any nicer?
    - The nerve is w.h.e. to the hocolim of a functor.
    - Explicitly.
      - $x\in M$, let $Q(x)$ be the category with
        - objects $(Q,Q\rightarrow x$ where Q$ is cofibrant and
          $Q\xrightarrow{~}X$.
      - for any object $Y$ in $M$,
        - $M(-,Y):Q(X)^{op}\rightarrow Set\hookrightarrow sSet$ where $(Q,Q\rightarrow
          X)\mapsto Hom(Q,Y)$
      - we can take $hocloim_({Q(x)^{op}M(-,Y)$
        1) take simplicial replacement of $M(-,Y)$
           - $n$-simplices are {{diagram from last class}}
             = $N([X\xleftarrow{~}Q\leftarrow Y])$
        2) take geometric realization
  - *Proposition* When $Y$ is fibrant, the maps in the following diagram are w.h.e
    on nerves
    #+BEGIN_SRC latex :file diag24.svg
      \begin{diagram}
        M(wfib)^{-1}(X,Y)&\rInto^{j_3}&M(wfib)^{-1}M(x,y)\\
        \dInto^{j_1}&&\dInto_{j_2}\\
        MW^{-1}(X,Y)&\rInto_{j_4}&MW^{-1}M(X,Y)
      \end{diagram}
    #+END_SRC
    - $(wcof)^{-1}M(wfib)^{-1}(X,Y)$ is $[X\xleftarrow{~}U\rightarrow
      V\xleftarrow{~}Y]$
    - similarly for other $M(wfib){^-1}$, etc.
    - $(wfib)\subseteq W$, $id\in M$, so all maps are inclusions
    - Proof
      1) Prove $j_1$ induces a w.e. of nerves
         - $[X\xleftarrow{~}U\rightarrow
           Y]\xrightarrow{j_1}[X\xleftarrow{~}Q\rightarrow Y]$
         - construct a functor back $F_1$
           - functorialy factor $A\rightarrow X\times Y$ as
             $A\hookrightarrow P\rightarrow X\times Y$
           - because $Y$ is fibrant $Y\rightarrow *$ is a fibration
             - *Fact$ fibrations are closed under pullback and
               cofibrations are closed under pushout.
             - closed under pullback, so $X\times Y\rightarrow X$ is a
               fibration
             - hence $P\rightarrow X$ is a fibration, and w.e. by 2-of-3
         - *Fact* if we have adjoint functors $(F,G)$ then the induced
           map $N(G)$ is a homotopy inverse to $N(F)$
      2) Prove $j_2$ induces a w.e. of nerves
         - $[X\rightarrow U\xleftarrow{~}V\rightarrow Y]\xrightarrow{j_1}[X\rightarrow U\xleftarrow{~}V\rightarrow Y]$
         - functorially factor $V\rightarrow U\times Y$
      3) $j_3$ (Don't need $Y$ fibrant
         - $[X\xleftarrow{~}P\rightarrow Y]\xrightarrow{j_1}[X\rightarrow U\xleftarrow{~}V\rightarrow Y]$
         - Let $P$ be the pullback of $X$ and $V$ over $U$.
      4) $j_4$ w.e by 2-of-3
         - $MW^{-1}(X,Y)\rightarrow MW^{-1}M(X,Y)$
    - Point: The nerve of any of these 4 categories of zigzags is
      w.e. to $Map^h(X,Y)$
**** $Hom(QX^*,X$ and $Hom(X,R_*Y)$
Leads naturally to models 2 and 3.
- Outline
  1) $QX^*\rightarrow X$ of $X$ in cM (Reedy model category associated
    to M.
     - $QX^*$ is bar resolution
    #+BEGIN_SRC latex :file diag25.svg
      \begn{diagram}
        X\otimes X\otems X
        \dLine\\
        X\otimes X &\rLine& X\\
        \dLine\\
        X
      \end{diagram}
    #+END_SRC
  2) For any simplicial set $K$ we have $\Delta K$ the category of
     simplicices
     - $\Delta K$ is overcategory $S\downarrow K$ where
       $S:\Delta\rightarrow sSet: [n]\mapsto \Delta^n$
     - The nerve of $\Delta K$ is w.h.e $K$
  3) We set up a function
     $\Delta Hom_M(QX^*,Y\rightarrow M(wfib)^{-1}(X,y)$ where
     $([n],QX^n\rightarrow Y)\mapsto[X\xleftarrow{~}QX^n\rightarrow Y]
- *Proposition* (DK, 1980)
  - Let $QX^*$ be a Reedy cofbirant replacement of $X$. Then
    - $\Delta Hom_M(QX^*,Y\rightarrow M(wfib)^{-1}(X,y)$
      is a w.h.e on nerves when $Y$is fibrant.
    - therefore $N(\Delta Hom_M(QX^*,Y))\simeq Hom_M(QX^*,Y)\simeq Map^h(X,Y)$.
